import type { Chain, Property, PropertyStatus, KeywordRanking } from "@/types/dashboard";

function status(vsLM: number, vsLY: number): PropertyStatus {
  if (vsLM < -10 || vsLY < -15) return "critical";
  if (vsLM < -4 || vsLY < -7) return "warning";
  return "healthy";
}

function kw(
  id: string,
  keyword: string,
  vol: number,
  cur: number | null,
  prev: number | null,
  url: string,
  comps: [string, number | null][]
): KeywordRanking {
  return {
    id,
    keyword,
    searchVolume: vol,
    currentRank: cur,
    previousRank: prev,
    rankChange: cur !== null && prev !== null ? prev - cur : null,
    targetUrl: url,
    competitors: comps.map(([domain, rank]) => ({ domain, rank })),
  };
}

// ─── CHAIN 1: Meridian Luxury Hotels ────────────────────────────────────────
const meridianProperties: Property[] = [
  {
    id: "mrd-london",
    chainId: "meridian",
    name: "Meridian London Hyde Park",
    location: "London, UK",
    gaPropertyId: "GA4-MRD-001",
    website: "meridian-london.com",
    status: status(-18.3, -24.1),
    metrics: {
      organicTraffic: { current: 12450, vsLastMonthPct: -18.3, vsLastYearPct: -24.1 },
      totalTraffic: { current: 18920, vsLastMonthPct: -14.2, vsLastYearPct: -19.8 },
      newUsersPct: 68, returningUsersPct: 32,
      bounceRate: 54.2, conversionRate: 1.8, roomNights: 284, revenue: 89500,
    },
    competitorDomains: ["marriott-london.com", "hilton-london.co.uk", "radisson-hyde.com"],
    keywords: [
      kw("mrd-lon-1", "luxury hotel london hyde park", 8100, 14, 18, "/rooms", [["marriott-london.com", 3], ["hilton-london.co.uk", 7], ["radisson-hyde.com", 11]]),
      kw("mrd-lon-2", "meridian london hotel", 2400, 1, 1, "/", [["marriott-london.com", null], ["hilton-london.co.uk", null], ["radisson-hyde.com", null]]),
      kw("mrd-lon-3", "best hotels hyde park", 5400, 22, 15, "/about", [["marriott-london.com", 4], ["hilton-london.co.uk", 9], ["radisson-hyde.com", 14]]),
      kw("mrd-lon-4", "london hotel deals", 12100, 38, 29, "/offers", [["marriott-london.com", 8], ["hilton-london.co.uk", 12], ["radisson-hyde.com", 21]]),
      kw("mrd-lon-5", "5 star hotels london", 9900, 11, 8, "/", [["marriott-london.com", 2], ["hilton-london.co.uk", 5], ["radisson-hyde.com", 16]]),
      kw("mrd-lon-6", "hotel near hyde park", 3600, 7, 6, "/location", [["marriott-london.com", 3], ["hilton-london.co.uk", 10], ["radisson-hyde.com", 13]]),
      kw("mrd-lon-7", "london luxury spa hotel", 2900, 19, 25, "/spa", [["marriott-london.com", 6], ["hilton-london.co.uk", null], ["radisson-hyde.com", 28]]),
      kw("mrd-lon-8", "london hotel room booking", 6600, 45, 33, "/book", [["marriott-london.com", 9], ["hilton-london.co.uk", 15], ["radisson-hyde.com", null]]),
    ],
  },
  {
    id: "mrd-paris",
    chainId: "meridian",
    name: "Meridian Paris Champs-Élysées",
    location: "Paris, France",
    gaPropertyId: "GA4-MRD-002",
    website: "meridian-paris.com",
    status: status(-6.1, -9.4),
    metrics: {
      organicTraffic: { current: 18730, vsLastMonthPct: -6.1, vsLastYearPct: -9.4 },
      totalTraffic: { current: 26800, vsLastMonthPct: -4.3, vsLastYearPct: -7.1 },
      newUsersPct: 72, returningUsersPct: 28,
      bounceRate: 48.6, conversionRate: 2.4, roomNights: 412, revenue: 143200,
    },
    competitorDomains: ["fourseasons-paris.com", "ritz-paris.com", "plaza-athenee.com"],
    keywords: [
      kw("mrd-par-1", "luxury hotel paris champs elysees", 9900, 8, 12, "/rooms", [["fourseasons-paris.com", 2], ["ritz-paris.com", 4], ["plaza-athenee.com", 6]]),
      kw("mrd-par-2", "meridian paris hotel", 1900, 1, 1, "/", [["fourseasons-paris.com", null], ["ritz-paris.com", null], ["plaza-athenee.com", null]]),
      kw("mrd-par-3", "best paris luxury hotels", 14800, 15, 18, "/", [["fourseasons-paris.com", 1], ["ritz-paris.com", 3], ["plaza-athenee.com", 7]]),
      kw("mrd-par-4", "paris hotel eiffel tower view", 6600, 12, 16, "/rooms/deluxe", [["fourseasons-paris.com", 5], ["ritz-paris.com", 8], ["plaza-athenee.com", 11]]),
      kw("mrd-par-5", "5 star hotel paris", 22200, 21, 25, "/", [["fourseasons-paris.com", 2], ["ritz-paris.com", 4], ["plaza-athenee.com", 9]]),
      kw("mrd-par-6", "romantic hotel paris", 8100, 9, 7, "/experiences", [["fourseasons-paris.com", 3], ["ritz-paris.com", 6], ["plaza-athenee.com", 14]]),
      kw("mrd-par-7", "paris boutique hotel deal", 4400, 28, 22, "/offers", [["fourseasons-paris.com", 7], ["ritz-paris.com", null], ["plaza-athenee.com", 17]]),
      kw("mrd-par-8", "hotel breakfast paris included", 3200, 17, 21, "/dining", [["fourseasons-paris.com", 4], ["ritz-paris.com", 9], ["plaza-athenee.com", 12]]),
    ],
  },
  {
    id: "mrd-dubai",
    chainId: "meridian",
    name: "Meridian Dubai Marina",
    location: "Dubai, UAE",
    gaPropertyId: "GA4-MRD-003",
    website: "meridian-dubai.com",
    status: status(9.2, 14.6),
    metrics: {
      organicTraffic: { current: 24100, vsLastMonthPct: 9.2, vsLastYearPct: 14.6 },
      totalTraffic: { current: 33400, vsLastMonthPct: 7.8, vsLastYearPct: 12.1 },
      newUsersPct: 81, returningUsersPct: 19,
      bounceRate: 41.3, conversionRate: 3.1, roomNights: 628, revenue: 218400,
    },
    competitorDomains: ["address-dubai.com", "atlantis-dubai.com", "burj-hotel.com"],
    keywords: [
      kw("mrd-dub-1", "luxury hotel dubai marina", 12100, 5, 9, "/rooms", [["address-dubai.com", 2], ["atlantis-dubai.com", 8], ["burj-hotel.com", 11]]),
      kw("mrd-dub-2", "meridian dubai hotel", 3200, 1, 1, "/", [["address-dubai.com", null], ["atlantis-dubai.com", null], ["burj-hotel.com", null]]),
      kw("mrd-dub-3", "dubai marina hotel deals", 8100, 7, 12, "/offers", [["address-dubai.com", 3], ["atlantis-dubai.com", 6], ["burj-hotel.com", 9]]),
      kw("mrd-dub-4", "5 star hotel dubai marina", 9900, 4, 7, "/", [["address-dubai.com", 1], ["atlantis-dubai.com", 10], ["burj-hotel.com", 15]]),
      kw("mrd-dub-5", "hotel pool dubai marina", 5400, 9, 14, "/amenities", [["address-dubai.com", 4], ["atlantis-dubai.com", 7], ["burj-hotel.com", 12]]),
      kw("mrd-dub-6", "dubai hotel sea view room", 6600, 6, 8, "/rooms/seaview", [["address-dubai.com", 2], ["atlantis-dubai.com", 11], ["burj-hotel.com", 14]]),
      kw("mrd-dub-7", "dubai new year hotel package", 4400, 14, 18, "/packages", [["address-dubai.com", 5], ["atlantis-dubai.com", 9], ["burj-hotel.com", 17]]),
      kw("mrd-dub-8", "book hotel dubai online", 18100, 19, 24, "/book", [["address-dubai.com", 7], ["atlantis-dubai.com", 13], ["burj-hotel.com", 22]]),
    ],
  },
  {
    id: "mrd-ny",
    chainId: "meridian",
    name: "Meridian New York Midtown",
    location: "New York, USA",
    gaPropertyId: "GA4-MRD-004",
    website: "meridian-newyork.com",
    status: status(4.1, 6.8),
    metrics: {
      organicTraffic: { current: 31200, vsLastMonthPct: 4.1, vsLastYearPct: 6.8 },
      totalTraffic: { current: 44800, vsLastMonthPct: 3.2, vsLastYearPct: 5.4 },
      newUsersPct: 75, returningUsersPct: 25,
      bounceRate: 43.8, conversionRate: 2.8, roomNights: 742, revenue: 267100,
    },
    competitorDomains: ["plaza-nyc.com", "waldorf-astoria.com", "the-mark-hotel.com"],
    keywords: [
      kw("mrd-ny-1", "luxury hotel new york midtown", 18100, 9, 11, "/rooms", [["plaza-nyc.com", 2], ["waldorf-astoria.com", 5], ["the-mark-hotel.com", 14]]),
      kw("mrd-ny-2", "meridian new york hotel", 2900, 1, 1, "/", [["plaza-nyc.com", null], ["waldorf-astoria.com", null], ["the-mark-hotel.com", null]]),
      kw("mrd-ny-3", "midtown manhattan hotel", 22200, 18, 24, "/", [["plaza-nyc.com", 3], ["waldorf-astoria.com", 8], ["the-mark-hotel.com", 16]]),
      kw("mrd-ny-4", "times square hotel deals", 27100, 24, 31, "/offers", [["plaza-nyc.com", 6], ["waldorf-astoria.com", 12], ["the-mark-hotel.com", 19]]),
      kw("mrd-ny-5", "5 star hotel manhattan", 14800, 12, 15, "/", [["plaza-nyc.com", 1], ["waldorf-astoria.com", 4], ["the-mark-hotel.com", 11]]),
      kw("mrd-ny-6", "new york hotel with gym spa", 8100, 8, 10, "/amenities", [["plaza-nyc.com", 3], ["waldorf-astoria.com", 6], ["the-mark-hotel.com", 17]]),
      kw("mrd-ny-7", "nyc hotel near central park", 9900, 16, 20, "/location", [["plaza-nyc.com", 2], ["waldorf-astoria.com", 9], ["the-mark-hotel.com", 13]]),
      kw("mrd-ny-8", "cheap luxury hotels new york", 33100, 31, 28, "/offers/lastminute", [["plaza-nyc.com", 8], ["waldorf-astoria.com", 14], ["the-mark-hotel.com", 22]]),
    ],
  },
  {
    id: "mrd-singapore",
    chainId: "meridian",
    name: "Meridian Singapore Orchard",
    location: "Singapore",
    gaPropertyId: "GA4-MRD-005",
    website: "meridian-singapore.com",
    status: status(-2.1, 3.4),
    metrics: {
      organicTraffic: { current: 16800, vsLastMonthPct: -2.1, vsLastYearPct: 3.4 },
      totalTraffic: { current: 23100, vsLastMonthPct: -1.4, vsLastYearPct: 2.8 },
      newUsersPct: 70, returningUsersPct: 30,
      bounceRate: 46.1, conversionRate: 2.2, roomNights: 398, revenue: 134600,
    },
    competitorDomains: ["marina-bay-sands.com", "raffles-singapore.com", "shangri-la.com"],
    keywords: [
      kw("mrd-sg-1", "luxury hotel singapore orchard road", 9900, 11, 13, "/rooms", [["marina-bay-sands.com", 2], ["raffles-singapore.com", 5], ["shangri-la.com", 8]]),
      kw("mrd-sg-2", "meridian singapore hotel", 1900, 1, 1, "/", [["marina-bay-sands.com", null], ["raffles-singapore.com", null], ["shangri-la.com", null]]),
      kw("mrd-sg-3", "best hotel orchard singapore", 6600, 8, 11, "/", [["marina-bay-sands.com", 1], ["raffles-singapore.com", 4], ["shangri-la.com", 7]]),
      kw("mrd-sg-4", "singapore 5 star hotel deal", 12100, 17, 22, "/offers", [["marina-bay-sands.com", 3], ["raffles-singapore.com", 9], ["shangri-la.com", 14]]),
      kw("mrd-sg-5", "hotel infinity pool singapore", 8100, 14, 16, "/amenities", [["marina-bay-sands.com", 1], ["raffles-singapore.com", 6], ["shangri-la.com", 11]]),
      kw("mrd-sg-6", "singapore family hotel orchard", 5400, 9, 8, "/family", [["marina-bay-sands.com", 4], ["raffles-singapore.com", 12], ["shangri-la.com", 16]]),
      kw("mrd-sg-7", "book hotel singapore best rate", 14800, 22, 27, "/book", [["marina-bay-sands.com", 6], ["raffles-singapore.com", 11], ["shangri-la.com", 18]]),
      kw("mrd-sg-8", "singapore luxury spa weekend", 4400, 19, 23, "/spa", [["marina-bay-sands.com", 5], ["raffles-singapore.com", 8], ["shangri-la.com", 13]]),
    ],
  },
  {
    id: "mrd-rome",
    chainId: "meridian",
    name: "Meridian Rome Colosseum View",
    location: "Rome, Italy",
    gaPropertyId: "GA4-MRD-006",
    website: "meridian-rome.com",
    status: status(-22.7, -31.4),
    metrics: {
      organicTraffic: { current: 8320, vsLastMonthPct: -22.7, vsLastYearPct: -31.4 },
      totalTraffic: { current: 11900, vsLastMonthPct: -19.1, vsLastYearPct: -27.3 },
      newUsersPct: 74, returningUsersPct: 26,
      bounceRate: 61.8, conversionRate: 1.1, roomNights: 121, revenue: 38200,
    },
    competitorDomains: ["hotel-hassler.com", "de-russie.com", "hotel-eden-rome.com"],
    keywords: [
      kw("mrd-rom-1", "luxury hotel rome colosseum", 6600, 28, 19, "/rooms", [["hotel-hassler.com", 3], ["de-russie.com", 7], ["hotel-eden-rome.com", 12]]),
      kw("mrd-rom-2", "meridian rome hotel", 880, 1, 1, "/", [["hotel-hassler.com", null], ["de-russie.com", null], ["hotel-eden-rome.com", null]]),
      kw("mrd-rom-3", "best hotel near colosseum rome", 8100, 34, 24, "/location", [["hotel-hassler.com", 4], ["de-russie.com", 8], ["hotel-eden-rome.com", 15]]),
      kw("mrd-rom-4", "5 star rome hotel deal", 9900, 41, 29, "/offers", [["hotel-hassler.com", 6], ["de-russie.com", 11], ["hotel-eden-rome.com", 18]]),
      kw("mrd-rom-5", "rome hotel breakfast included", 5400, 37, 26, "/dining", [["hotel-hassler.com", 5], ["de-russie.com", 9], ["hotel-eden-rome.com", 16]]),
      kw("mrd-rom-6", "romantic hotel rome italy", 7200, 22, 14, "/experiences", [["hotel-hassler.com", 2], ["de-russie.com", 6], ["hotel-eden-rome.com", 10]]),
      kw("mrd-rom-7", "rome hotel terrace view", 3600, 31, 21, "/rooms/suite", [["hotel-hassler.com", 4], ["de-russie.com", 8], ["hotel-eden-rome.com", 14]]),
      kw("mrd-rom-8", "book rome hotel online cheap", 14800, 49, 37, "/book", [["hotel-hassler.com", 9], ["de-russie.com", 16], ["hotel-eden-rome.com", 24]]),
    ],
  },
  {
    id: "mrd-tokyo",
    chainId: "meridian",
    name: "Meridian Tokyo Shinjuku",
    location: "Tokyo, Japan",
    gaPropertyId: "GA4-MRD-007",
    website: "meridian-tokyo.com",
    status: status(11.8, 18.3),
    metrics: {
      organicTraffic: { current: 21400, vsLastMonthPct: 11.8, vsLastYearPct: 18.3 },
      totalTraffic: { current: 29800, vsLastMonthPct: 9.4, vsLastYearPct: 15.7 },
      newUsersPct: 83, returningUsersPct: 17,
      bounceRate: 38.4, conversionRate: 3.4, roomNights: 561, revenue: 196700,
    },
    competitorDomains: ["park-hyatt-tokyo.com", "aman-tokyo.com", "peninsula-tokyo.com"],
    keywords: [
      kw("mrd-tok-1", "luxury hotel tokyo shinjuku", 8100, 6, 9, "/rooms", [["park-hyatt-tokyo.com", 2], ["aman-tokyo.com", 4], ["peninsula-tokyo.com", 8]]),
      kw("mrd-tok-2", "meridian tokyo hotel", 2100, 1, 1, "/", [["park-hyatt-tokyo.com", null], ["aman-tokyo.com", null], ["peninsula-tokyo.com", null]]),
      kw("mrd-tok-3", "best hotel shinjuku tokyo", 12100, 4, 7, "/", [["park-hyatt-tokyo.com", 1], ["aman-tokyo.com", 5], ["peninsula-tokyo.com", 9]]),
      kw("mrd-tok-4", "tokyo hotel deals 2024", 22200, 14, 19, "/offers", [["park-hyatt-tokyo.com", 5], ["aman-tokyo.com", 8], ["peninsula-tokyo.com", 12]]),
      kw("mrd-tok-5", "5 star hotel tokyo", 18100, 11, 15, "/", [["park-hyatt-tokyo.com", 2], ["aman-tokyo.com", 6], ["peninsula-tokyo.com", 10]]),
      kw("mrd-tok-6", "tokyo hotel mount fuji view", 4400, 8, 13, "/rooms/premium", [["park-hyatt-tokyo.com", 3], ["aman-tokyo.com", 7], ["peninsula-tokyo.com", 11]]),
      kw("mrd-tok-7", "tokyo luxury business hotel", 6600, 9, 12, "/business", [["park-hyatt-tokyo.com", 4], ["aman-tokyo.com", 6], ["peninsula-tokyo.com", 14]]),
      kw("mrd-tok-8", "shinjuku hotel online booking", 9900, 16, 21, "/book", [["park-hyatt-tokyo.com", 6], ["aman-tokyo.com", 10], ["peninsula-tokyo.com", 17]]),
    ],
  },
  {
    id: "mrd-sydney",
    chainId: "meridian",
    name: "Meridian Sydney Harbour",
    location: "Sydney, Australia",
    gaPropertyId: "GA4-MRD-008",
    website: "meridian-sydney.com",
    status: status(1.3, -4.2),
    metrics: {
      organicTraffic: { current: 14900, vsLastMonthPct: 1.3, vsLastYearPct: -4.2 },
      totalTraffic: { current: 21300, vsLastMonthPct: 0.9, vsLastYearPct: -3.1 },
      newUsersPct: 69, returningUsersPct: 31,
      bounceRate: 45.7, conversionRate: 2.1, roomNights: 337, revenue: 118400,
    },
    competitorDomains: ["park-hyatt-sydney.com", "shangri-la-sydney.com", "four-seasons-sydney.com"],
    keywords: [
      kw("mrd-syd-1", "luxury hotel sydney harbour", 9900, 10, 12, "/rooms", [["park-hyatt-sydney.com", 1], ["shangri-la-sydney.com", 4], ["four-seasons-sydney.com", 7]]),
      kw("mrd-syd-2", "meridian sydney hotel", 1600, 1, 1, "/", [["park-hyatt-sydney.com", null], ["shangri-la-sydney.com", null], ["four-seasons-sydney.com", null]]),
      kw("mrd-syd-3", "sydney harbour view hotel", 8100, 7, 9, "/rooms/harbour", [["park-hyatt-sydney.com", 2], ["shangri-la-sydney.com", 5], ["four-seasons-sydney.com", 8]]),
      kw("mrd-syd-4", "best sydney hotel cbd", 12100, 13, 16, "/", [["park-hyatt-sydney.com", 3], ["shangri-la-sydney.com", 7], ["four-seasons-sydney.com", 11]]),
      kw("mrd-syd-5", "5 star hotel sydney deals", 8100, 21, 25, "/offers", [["park-hyatt-sydney.com", 5], ["shangri-la-sydney.com", 9], ["four-seasons-sydney.com", 14]]),
      kw("mrd-syd-6", "sydney hotel opera house", 6600, 9, 11, "/location", [["park-hyatt-sydney.com", 2], ["shangri-la-sydney.com", 6], ["four-seasons-sydney.com", 10]]),
      kw("mrd-syd-7", "sydney hotel weekend getaway", 5400, 17, 22, "/packages", [["park-hyatt-sydney.com", 6], ["shangri-la-sydney.com", 11], ["four-seasons-sydney.com", 16]]),
      kw("mrd-syd-8", "book sydney luxury hotel", 14800, 24, 29, "/book", [["park-hyatt-sydney.com", 8], ["shangri-la-sydney.com", 13], ["four-seasons-sydney.com", 18]]),
    ],
  },
];

// ─── CHAIN 2: Crestview Resorts ──────────────────────────────────────────────
const crestviewProperties: Property[] = [
  {
    id: "crv-maldives",
    chainId: "crestview",
    name: "Crestview Maldives Overwater",
    location: "Maldives",
    gaPropertyId: "GA4-CRV-001",
    website: "crestview-maldives.com",
    status: status(16.4, 22.8),
    metrics: {
      organicTraffic: { current: 28900, vsLastMonthPct: 16.4, vsLastYearPct: 22.8 },
      totalTraffic: { current: 38400, vsLastMonthPct: 14.1, vsLastYearPct: 19.6 },
      newUsersPct: 88, returningUsersPct: 12,
      bounceRate: 32.1, conversionRate: 4.2, roomNights: 814, revenue: 368200,
    },
    competitorDomains: ["soneva-maldives.com", "gili-lankanfushi.com", "anantara-maldives.com"],
    keywords: [
      kw("crv-mal-1", "overwater bungalow maldives resort", 22200, 4, 7, "/villas", [["soneva-maldives.com", 1], ["gili-lankanfushi.com", 3], ["anantara-maldives.com", 6]]),
      kw("crv-mal-2", "crestview maldives resort", 3200, 1, 1, "/", [["soneva-maldives.com", null], ["gili-lankanfushi.com", null], ["anantara-maldives.com", null]]),
      kw("crv-mal-3", "best maldives resort 2024", 33100, 8, 12, "/", [["soneva-maldives.com", 2], ["gili-lankanfushi.com", 5], ["anantara-maldives.com", 9]]),
      kw("crv-mal-4", "maldives honeymoon resort", 18100, 6, 9, "/honeymoon", [["soneva-maldives.com", 2], ["gili-lankanfushi.com", 4], ["anantara-maldives.com", 8]]),
      kw("crv-mal-5", "maldives all inclusive deal", 27100, 11, 16, "/offers", [["soneva-maldives.com", 3], ["gili-lankanfushi.com", 7], ["anantara-maldives.com", 13]]),
      kw("crv-mal-6", "water villa maldives price", 14800, 9, 14, "/villas/water", [["soneva-maldives.com", 2], ["gili-lankanfushi.com", 5], ["anantara-maldives.com", 11]]),
      kw("crv-mal-7", "maldives resort diving snorkeling", 8100, 5, 8, "/activities", [["soneva-maldives.com", 1], ["gili-lankanfushi.com", 4], ["anantara-maldives.com", 7]]),
      kw("crv-mal-8", "book maldives villa luxury", 9900, 14, 19, "/book", [["soneva-maldives.com", 4], ["gili-lankanfushi.com", 8], ["anantara-maldives.com", 12]]),
    ],
  },
  {
    id: "crv-bali",
    chainId: "crestview",
    name: "Crestview Bali Ubud Retreat",
    location: "Bali, Indonesia",
    gaPropertyId: "GA4-CRV-002",
    website: "crestview-bali.com",
    status: status(-13.6, -19.8),
    metrics: {
      organicTraffic: { current: 19200, vsLastMonthPct: -13.6, vsLastYearPct: -19.8 },
      totalTraffic: { current: 26700, vsLastMonthPct: -11.2, vsLastYearPct: -16.4 },
      newUsersPct: 77, returningUsersPct: 23,
      bounceRate: 51.4, conversionRate: 2.0, roomNights: 298, revenue: 94800,
    },
    competitorDomains: ["alaya-ubud.com", "como-shambhala.com", "four-seasons-bali.com"],
    keywords: [
      kw("crv-bal-1", "luxury resort bali ubud", 14800, 19, 12, "/rooms", [["alaya-ubud.com", 2], ["como-shambhala.com", 5], ["four-seasons-bali.com", 8]]),
      kw("crv-bal-2", "crestview bali resort", 2100, 1, 1, "/", [["alaya-ubud.com", null], ["como-shambhala.com", null], ["four-seasons-bali.com", null]]),
      kw("crv-bal-3", "best bali jungle resort", 18100, 26, 18, "/", [["alaya-ubud.com", 3], ["como-shambhala.com", 7], ["four-seasons-bali.com", 11]]),
      kw("crv-bal-4", "bali yoga retreat resort", 9900, 22, 15, "/wellness", [["alaya-ubud.com", 4], ["como-shambhala.com", 6], ["four-seasons-bali.com", 10]]),
      kw("crv-bal-5", "ubud rice terrace hotel", 6600, 31, 22, "/location", [["alaya-ubud.com", 5], ["como-shambhala.com", 9], ["four-seasons-bali.com", 14]]),
      kw("crv-bal-6", "bali all inclusive resort", 22200, 37, 25, "/offers", [["alaya-ubud.com", 7], ["como-shambhala.com", 12], ["four-seasons-bali.com", 16]]),
      kw("crv-bal-7", "bali spa hotel ubud", 8100, 24, 17, "/spa", [["alaya-ubud.com", 3], ["como-shambhala.com", 8], ["four-seasons-bali.com", 13]]),
      kw("crv-bal-8", "book bali resort cheapest rate", 12100, 42, 31, "/book", [["alaya-ubud.com", 9], ["como-shambhala.com", 14], ["four-seasons-bali.com", 21]]),
    ],
  },
  {
    id: "crv-phuket",
    chainId: "crestview",
    name: "Crestview Phuket Beachfront",
    location: "Phuket, Thailand",
    gaPropertyId: "GA4-CRV-003",
    website: "crestview-phuket.com",
    status: status(5.8, 8.4),
    metrics: {
      organicTraffic: { current: 22100, vsLastMonthPct: 5.8, vsLastYearPct: 8.4 },
      totalTraffic: { current: 31400, vsLastMonthPct: 4.6, vsLastYearPct: 6.9 },
      newUsersPct: 79, returningUsersPct: 21,
      bounceRate: 39.7, conversionRate: 3.3, roomNights: 524, revenue: 164200,
    },
    competitorDomains: ["trisara-phuket.com", "amanpuri.com", "como-phuket.com"],
    keywords: [
      kw("crv-phu-1", "luxury beachfront resort phuket", 18100, 7, 10, "/rooms", [["trisara-phuket.com", 2], ["amanpuri.com", 4], ["como-phuket.com", 9]]),
      kw("crv-phu-2", "crestview phuket resort", 2400, 1, 1, "/", [["trisara-phuket.com", null], ["amanpuri.com", null], ["como-phuket.com", null]]),
      kw("crv-phu-3", "phuket 5 star resort private beach", 12100, 9, 13, "/beachfront", [["trisara-phuket.com", 3], ["amanpuri.com", 6], ["como-phuket.com", 11]]),
      kw("crv-phu-4", "phuket resort deal package", 22200, 16, 21, "/offers", [["trisara-phuket.com", 5], ["amanpuri.com", 9], ["como-phuket.com", 14]]),
      kw("crv-phu-5", "patong beach hotel luxury", 9900, 12, 15, "/location", [["trisara-phuket.com", 4], ["amanpuri.com", 7], ["como-phuket.com", 12]]),
      kw("crv-phu-6", "phuket honeymoon resort", 8100, 8, 11, "/honeymoon", [["trisara-phuket.com", 3], ["amanpuri.com", 5], ["como-phuket.com", 10]]),
      kw("crv-phu-7", "thailand island resort snorkel dive", 6600, 14, 18, "/activities", [["trisara-phuket.com", 5], ["amanpuri.com", 8], ["como-phuket.com", 13]]),
      kw("crv-phu-8", "phuket hotel book direct best rate", 14800, 21, 26, "/book", [["trisara-phuket.com", 7], ["amanpuri.com", 11], ["como-phuket.com", 16]]),
    ],
  },
  {
    id: "crv-cancun",
    chainId: "crestview",
    name: "Crestview Cancún Ocean View",
    location: "Cancún, Mexico",
    gaPropertyId: "GA4-CRV-004",
    website: "crestview-cancun.com",
    status: status(-7.4, -11.2),
    metrics: {
      organicTraffic: { current: 17800, vsLastMonthPct: -7.4, vsLastYearPct: -11.2 },
      totalTraffic: { current: 25200, vsLastMonthPct: -5.8, vsLastYearPct: -9.1 },
      newUsersPct: 82, returningUsersPct: 18,
      bounceRate: 49.3, conversionRate: 2.4, roomNights: 386, revenue: 123400,
    },
    competitorDomains: ["moon-palace.com", "live-aqua-cancun.com", "le-blanc-spa.com"],
    keywords: [
      kw("crv-can-1", "all inclusive resort cancun", 49500, 22, 16, "/all-inclusive", [["moon-palace.com", 3], ["live-aqua-cancun.com", 7], ["le-blanc-spa.com", 11]]),
      kw("crv-can-2", "crestview cancun resort", 1900, 1, 1, "/", [["moon-palace.com", null], ["live-aqua-cancun.com", null], ["le-blanc-spa.com", null]]),
      kw("crv-can-3", "luxury cancun resort oceanfront", 14800, 29, 21, "/rooms", [["moon-palace.com", 4], ["live-aqua-cancun.com", 9], ["le-blanc-spa.com", 14]]),
      kw("crv-can-4", "cancun hotel zone deals", 33100, 41, 31, "/offers", [["moon-palace.com", 7], ["live-aqua-cancun.com", 12], ["le-blanc-spa.com", 18]]),
      kw("crv-can-5", "adults only resort cancun", 18100, 18, 12, "/adults-only", [["moon-palace.com", 5], ["live-aqua-cancun.com", 8], ["le-blanc-spa.com", 10]]),
      kw("crv-can-6", "cancun resort swim up bar", 8100, 26, 19, "/amenities", [["moon-palace.com", 6], ["live-aqua-cancun.com", 11], ["le-blanc-spa.com", 16]]),
      kw("crv-can-7", "cancun spring break hotel", 12100, 34, 26, "/packages/springbreak", [["moon-palace.com", 8], ["live-aqua-cancun.com", 14], ["le-blanc-spa.com", 20]]),
      kw("crv-can-8", "book cancun resort direct", 22200, 47, 36, "/book", [["moon-palace.com", 10], ["live-aqua-cancun.com", 16], ["le-blanc-spa.com", 23]]),
    ],
  },
  {
    id: "crv-santorini",
    chainId: "crestview",
    name: "Crestview Santorini Caldera",
    location: "Santorini, Greece",
    gaPropertyId: "GA4-CRV-005",
    website: "crestview-santorini.com",
    status: status(8.1, 12.6),
    metrics: {
      organicTraffic: { current: 16400, vsLastMonthPct: 8.1, vsLastYearPct: 12.6 },
      totalTraffic: { current: 22800, vsLastMonthPct: 6.9, vsLastYearPct: 10.4 },
      newUsersPct: 76, returningUsersPct: 24,
      bounceRate: 37.2, conversionRate: 3.8, roomNights: 438, revenue: 197800,
    },
    competitorDomains: ["grace-hotel.com", "canaves-oia.com", "andronis-luxury.com"],
    keywords: [
      kw("crv-san-1", "luxury hotel santorini caldera view", 12100, 6, 9, "/suites", [["grace-hotel.com", 2], ["canaves-oia.com", 4], ["andronis-luxury.com", 7]]),
      kw("crv-san-2", "crestview santorini resort", 1600, 1, 1, "/", [["grace-hotel.com", null], ["canaves-oia.com", null], ["andronis-luxury.com", null]]),
      kw("crv-san-3", "oia santorini hotel infinity pool", 18100, 8, 12, "/amenities", [["grace-hotel.com", 3], ["canaves-oia.com", 5], ["andronis-luxury.com", 9]]),
      kw("crv-san-4", "santorini honeymoon suite", 14800, 7, 11, "/honeymoon", [["grace-hotel.com", 2], ["canaves-oia.com", 4], ["andronis-luxury.com", 8]]),
      kw("crv-san-5", "best santorini hotel sunset view", 22200, 11, 15, "/", [["grace-hotel.com", 4], ["canaves-oia.com", 7], ["andronis-luxury.com", 12]]),
      kw("crv-san-6", "santorini cave hotel suite", 9900, 9, 13, "/suites/cave", [["grace-hotel.com", 3], ["canaves-oia.com", 6], ["andronis-luxury.com", 10]]),
      kw("crv-san-7", "santorini winery hotel tour", 5400, 14, 18, "/experiences", [["grace-hotel.com", 5], ["canaves-oia.com", 9], ["andronis-luxury.com", 14]]),
      kw("crv-san-8", "book santorini luxury suite direct", 8100, 19, 23, "/book", [["grace-hotel.com", 7], ["canaves-oia.com", 11], ["andronis-luxury.com", 16]]),
    ],
  },
  {
    id: "crv-abudhabi",
    chainId: "crestview",
    name: "Crestview Abu Dhabi Corniche",
    location: "Abu Dhabi, UAE",
    gaPropertyId: "GA4-CRV-006",
    website: "crestview-abudhabi.com",
    status: status(3.2, -5.8),
    metrics: {
      organicTraffic: { current: 13400, vsLastMonthPct: 3.2, vsLastYearPct: -5.8 },
      totalTraffic: { current: 19100, vsLastMonthPct: 2.6, vsLastYearPct: -4.3 },
      newUsersPct: 73, returningUsersPct: 27,
      bounceRate: 44.8, conversionRate: 2.7, roomNights: 318, revenue: 112600,
    },
    competitorDomains: ["emirates-palace.com", "rosewood-abu-dhabi.com", "st-regis-abudhabi.com"],
    keywords: [
      kw("crv-ad-1", "luxury hotel abu dhabi corniche", 8100, 12, 15, "/rooms", [["emirates-palace.com", 1], ["rosewood-abu-dhabi.com", 4], ["st-regis-abudhabi.com", 7]]),
      kw("crv-ad-2", "crestview abu dhabi hotel", 1100, 1, 1, "/", [["emirates-palace.com", null], ["rosewood-abu-dhabi.com", null], ["st-regis-abudhabi.com", null]]),
      kw("crv-ad-3", "abu dhabi 5 star hotel beach", 9900, 16, 20, "/beachfront", [["emirates-palace.com", 2], ["rosewood-abu-dhabi.com", 6], ["st-regis-abudhabi.com", 10]]),
      kw("crv-ad-4", "abu dhabi hotel weekend deal", 6600, 24, 29, "/offers", [["emirates-palace.com", 5], ["rosewood-abu-dhabi.com", 9], ["st-regis-abudhabi.com", 14]]),
      kw("crv-ad-5", "family hotel abu dhabi", 12100, 19, 23, "/family", [["emirates-palace.com", 3], ["rosewood-abu-dhabi.com", 7], ["st-regis-abudhabi.com", 12]]),
      kw("crv-ad-6", "abu dhabi hotel yas island", 8100, 28, 33, "/packages", [["emirates-palace.com", 6], ["rosewood-abu-dhabi.com", 11], ["st-regis-abudhabi.com", 17]]),
      kw("crv-ad-7", "abu dhabi business hotel conference", 5400, 14, 18, "/meetings", [["emirates-palace.com", 4], ["rosewood-abu-dhabi.com", 8], ["st-regis-abudhabi.com", 13]]),
      kw("crv-ad-8", "book abu dhabi luxury resort", 9900, 31, 36, "/book", [["emirates-palace.com", 8], ["rosewood-abu-dhabi.com", 13], ["st-regis-abudhabi.com", 19]]),
    ],
  },
];

// ─── CHAIN 3: Heritage Palace Hotels ────────────────────────────────────────
const heritageProperties: Property[] = [
  {
    id: "hph-jaipur",
    chainId: "heritage",
    name: "Heritage Palace Jaipur",
    location: "Jaipur, India",
    gaPropertyId: "GA4-HPH-001",
    website: "heritage-jaipur.com",
    status: status(-25.3, -33.7),
    metrics: {
      organicTraffic: { current: 6840, vsLastMonthPct: -25.3, vsLastYearPct: -33.7 },
      totalTraffic: { current: 9800, vsLastMonthPct: -21.4, vsLastYearPct: -29.1 },
      newUsersPct: 69, returningUsersPct: 31,
      bounceRate: 64.2, conversionRate: 0.9, roomNights: 78, revenue: 24600,
    },
    competitorDomains: ["taj-rambagh.com", "oberoi-rajvilas.com", "aman-bagh.com"],
    keywords: [
      kw("hph-jai-1", "heritage palace hotel jaipur", 8100, 33, 21, "/rooms", [["taj-rambagh.com", 2], ["oberoi-rajvilas.com", 5], ["aman-bagh.com", 9]]),
      kw("hph-jai-2", "heritage jaipur palace", 2400, 1, 1, "/", [["taj-rambagh.com", null], ["oberoi-rajvilas.com", null], ["aman-bagh.com", null]]),
      kw("hph-jai-3", "luxury hotel jaipur pink city", 12100, 41, 28, "/", [["taj-rambagh.com", 3], ["oberoi-rajvilas.com", 7], ["aman-bagh.com", 12]]),
      kw("hph-jai-4", "rajasthan palace hotel deal", 9900, 47, 33, "/offers", [["taj-rambagh.com", 5], ["oberoi-rajvilas.com", 10], ["aman-bagh.com", 16]]),
      kw("hph-jai-5", "jaipur fort palace stay", 6600, 38, 26, "/experiences", [["taj-rambagh.com", 4], ["oberoi-rajvilas.com", 8], ["aman-bagh.com", 13]]),
      kw("hph-jai-6", "india palace hotel luxury", 8100, 29, 19, "/", [["taj-rambagh.com", 3], ["oberoi-rajvilas.com", 6], ["aman-bagh.com", 10]]),
      kw("hph-jai-7", "jaipur wedding venue palace", 5400, 22, 15, "/weddings", [["taj-rambagh.com", 2], ["oberoi-rajvilas.com", 5], ["aman-bagh.com", 8]]),
      kw("hph-jai-8", "book jaipur palace hotel online", 14800, 51, 39, "/book", [["taj-rambagh.com", 7], ["oberoi-rajvilas.com", 12], ["aman-bagh.com", 19]]),
    ],
  },
  {
    id: "hph-udaipur",
    chainId: "heritage",
    name: "Heritage Palace Udaipur Lake",
    location: "Udaipur, India",
    gaPropertyId: "GA4-HPH-002",
    website: "heritage-udaipur.com",
    status: status(-8.6, -12.4),
    metrics: {
      organicTraffic: { current: 9200, vsLastMonthPct: -8.6, vsLastYearPct: -12.4 },
      totalTraffic: { current: 13100, vsLastMonthPct: -7.1, vsLastYearPct: -10.2 },
      newUsersPct: 71, returningUsersPct: 29,
      bounceRate: 55.8, conversionRate: 1.4, roomNights: 148, revenue: 56800,
    },
    competitorDomains: ["taj-lake-palace.com", "oberoi-udaivilas.com", "lebua-udaipur.com"],
    keywords: [
      kw("hph-uda-1", "palace hotel udaipur lake", 9900, 17, 12, "/rooms", [["taj-lake-palace.com", 1], ["oberoi-udaivilas.com", 4], ["lebua-udaipur.com", 8]]),
      kw("hph-uda-2", "heritage udaipur palace hotel", 1900, 1, 1, "/", [["taj-lake-palace.com", null], ["oberoi-udaivilas.com", null], ["lebua-udaipur.com", null]]),
      kw("hph-uda-3", "udaipur lake view hotel", 12100, 22, 16, "/rooms/lakeview", [["taj-lake-palace.com", 2], ["oberoi-udaivilas.com", 6], ["lebua-udaipur.com", 11]]),
      kw("hph-uda-4", "luxury rajasthan heritage hotel", 8100, 29, 21, "/", [["taj-lake-palace.com", 3], ["oberoi-udaivilas.com", 8], ["lebua-udaipur.com", 14]]),
      kw("hph-uda-5", "udaipur honeymoon hotel", 7200, 14, 10, "/honeymoon", [["taj-lake-palace.com", 2], ["oberoi-udaivilas.com", 5], ["lebua-udaipur.com", 9]]),
      kw("hph-uda-6", "india royal palace stay experience", 6600, 26, 19, "/experiences", [["taj-lake-palace.com", 4], ["oberoi-udaivilas.com", 9], ["lebua-udaipur.com", 15]]),
      kw("hph-uda-7", "udaipur hotel boat ride lake pichola", 4400, 18, 13, "/activities", [["taj-lake-palace.com", 3], ["oberoi-udaivilas.com", 7], ["lebua-udaipur.com", 12]]),
      kw("hph-uda-8", "book heritage udaipur hotel", 9900, 37, 28, "/book", [["taj-lake-palace.com", 6], ["oberoi-udaivilas.com", 11], ["lebua-udaipur.com", 18]]),
    ],
  },
  {
    id: "hph-agra",
    chainId: "heritage",
    name: "Heritage Palace Agra Taj View",
    location: "Agra, India",
    gaPropertyId: "GA4-HPH-003",
    website: "heritage-agra.com",
    status: status(7.4, 11.2),
    metrics: {
      organicTraffic: { current: 11800, vsLastMonthPct: 7.4, vsLastYearPct: 11.2 },
      totalTraffic: { current: 16900, vsLastMonthPct: 6.1, vsLastYearPct: 9.3 },
      newUsersPct: 73, returningUsersPct: 27,
      bounceRate: 43.6, conversionRate: 2.3, roomNights: 236, revenue: 78400,
    },
    competitorDomains: ["oberoi-amarvilas.com", "ita-mughal.com", "trident-agra.com"],
    keywords: [
      kw("hph-agr-1", "hotel agra taj mahal view", 14800, 9, 13, "/rooms/tajview", [["oberoi-amarvilas.com", 1], ["ita-mughal.com", 5], ["trident-agra.com", 9]]),
      kw("hph-agr-2", "heritage agra palace hotel", 1600, 1, 1, "/", [["oberoi-amarvilas.com", null], ["ita-mughal.com", null], ["trident-agra.com", null]]),
      kw("hph-agr-3", "luxury hotel near taj mahal agra", 18100, 12, 17, "/location", [["oberoi-amarvilas.com", 2], ["ita-mughal.com", 6], ["trident-agra.com", 11]]),
      kw("hph-agr-4", "agra hotel sunrise taj mahal", 9900, 8, 12, "/rooms/suite", [["oberoi-amarvilas.com", 2], ["ita-mughal.com", 4], ["trident-agra.com", 8]]),
      kw("hph-agr-5", "india heritage tour hotel agra", 8100, 14, 19, "/packages", [["oberoi-amarvilas.com", 3], ["ita-mughal.com", 7], ["trident-agra.com", 12]]),
      kw("hph-agr-6", "agra hotel deal golden triangle", 6600, 18, 23, "/offers", [["oberoi-amarvilas.com", 5], ["ita-mughal.com", 9], ["trident-agra.com", 14]]),
      kw("hph-agr-7", "5 star hotel agra india", 12100, 21, 26, "/", [["oberoi-amarvilas.com", 4], ["ita-mughal.com", 8], ["trident-agra.com", 13]]),
      kw("hph-agr-8", "book agra luxury hotel direct", 9900, 28, 33, "/book", [["oberoi-amarvilas.com", 7], ["ita-mughal.com", 12], ["trident-agra.com", 18]]),
    ],
  },
  {
    id: "hph-jodhpur",
    chainId: "heritage",
    name: "Heritage Palace Jodhpur Blue City",
    location: "Jodhpur, India",
    gaPropertyId: "GA4-HPH-004",
    website: "heritage-jodhpur.com",
    status: status(2.6, 4.8),
    metrics: {
      organicTraffic: { current: 8400, vsLastMonthPct: 2.6, vsLastYearPct: 4.8 },
      totalTraffic: { current: 11900, vsLastMonthPct: 1.9, vsLastYearPct: 3.6 },
      newUsersPct: 68, returningUsersPct: 32,
      bounceRate: 47.3, conversionRate: 1.9, roomNights: 176, revenue: 58200,
    },
    competitorDomains: ["umaid-bhawan.com", "ajit-bhawan.com", "raas-jodhpur.com"],
    keywords: [
      kw("hph-jod-1", "palace hotel jodhpur blue city", 7200, 11, 14, "/rooms", [["umaid-bhawan.com", 1], ["ajit-bhawan.com", 5], ["raas-jodhpur.com", 8]]),
      kw("hph-jod-2", "heritage jodhpur palace hotel", 1100, 1, 1, "/", [["umaid-bhawan.com", null], ["ajit-bhawan.com", null], ["raas-jodhpur.com", null]]),
      kw("hph-jod-3", "jodhpur fort view hotel", 5400, 9, 12, "/rooms/fortview", [["umaid-bhawan.com", 2], ["ajit-bhawan.com", 6], ["raas-jodhpur.com", 9]]),
      kw("hph-jod-4", "luxury rajasthan fort hotel", 8100, 16, 20, "/", [["umaid-bhawan.com", 3], ["ajit-bhawan.com", 7], ["raas-jodhpur.com", 11]]),
      kw("hph-jod-5", "jodhpur blue city tour hotel", 6600, 13, 17, "/experiences", [["umaid-bhawan.com", 4], ["ajit-bhawan.com", 8], ["raas-jodhpur.com", 13]]),
      kw("hph-jod-6", "india desert safari heritage hotel", 4400, 19, 24, "/activities", [["umaid-bhawan.com", 5], ["ajit-bhawan.com", 10], ["raas-jodhpur.com", 15]]),
      kw("hph-jod-7", "jodhpur rooftop restaurant hotel", 3600, 8, 10, "/dining", [["umaid-bhawan.com", 2], ["ajit-bhawan.com", 6], ["raas-jodhpur.com", 11]]),
      kw("hph-jod-8", "book jodhpur heritage hotel", 8100, 24, 29, "/book", [["umaid-bhawan.com", 6], ["ajit-bhawan.com", 11], ["raas-jodhpur.com", 17]]),
    ],
  },
  {
    id: "hph-mysore",
    chainId: "heritage",
    name: "Heritage Palace Mysore",
    location: "Mysore, India",
    gaPropertyId: "GA4-HPH-005",
    website: "heritage-mysore.com",
    status: status(-3.8, 1.4),
    metrics: {
      organicTraffic: { current: 7100, vsLastMonthPct: -3.8, vsLastYearPct: 1.4 },
      totalTraffic: { current: 10200, vsLastMonthPct: -2.9, vsLastYearPct: 0.9 },
      newUsersPct: 65, returningUsersPct: 35,
      bounceRate: 50.1, conversionRate: 1.7, roomNights: 142, revenue: 44800,
    },
    competitorDomains: ["lalitha-mahal.com", "radisson-mysore.com", "hotel-dasaprakash.com"],
    keywords: [
      kw("hph-mys-1", "heritage palace hotel mysore", 4400, 8, 10, "/rooms", [["lalitha-mahal.com", 2], ["radisson-mysore.com", 5], ["hotel-dasaprakash.com", 9]]),
      kw("hph-mys-2", "heritage mysore palace stay", 880, 1, 1, "/", [["lalitha-mahal.com", null], ["radisson-mysore.com", null], ["hotel-dasaprakash.com", null]]),
      kw("hph-mys-3", "luxury hotel mysore karnataka", 6600, 13, 16, "/", [["lalitha-mahal.com", 3], ["radisson-mysore.com", 7], ["hotel-dasaprakash.com", 11]]),
      kw("hph-mys-4", "mysore dasara festival hotel", 5400, 9, 12, "/packages/dasara", [["lalitha-mahal.com", 2], ["radisson-mysore.com", 6], ["hotel-dasaprakash.com", 10]]),
      kw("hph-mys-5", "mysore palace view hotel", 8100, 11, 14, "/rooms/palaceview", [["lalitha-mahal.com", 3], ["radisson-mysore.com", 7], ["hotel-dasaprakash.com", 13]]),
      kw("hph-mys-6", "karnataka heritage tour hotel", 4400, 16, 19, "/experiences", [["lalitha-mahal.com", 4], ["radisson-mysore.com", 9], ["hotel-dasaprakash.com", 14]]),
      kw("hph-mys-7", "mysore zoo garden hotel near", 3600, 12, 15, "/location", [["lalitha-mahal.com", 5], ["radisson-mysore.com", 8], ["hotel-dasaprakash.com", 12]]),
      kw("hph-mys-8", "book heritage mysore hotel", 6600, 21, 25, "/book", [["lalitha-mahal.com", 7], ["radisson-mysore.com", 12], ["hotel-dasaprakash.com", 17]]),
    ],
  },
];

// ─── CHAIN 4: Zenith Business Hotels ────────────────────────────────────────
const zenithProperties: Property[] = [
  {
    id: "zbh-amsterdam",
    chainId: "zenith",
    name: "Zenith Amsterdam Schiphol",
    location: "Amsterdam, Netherlands",
    gaPropertyId: "GA4-ZBH-001",
    website: "zenith-amsterdam.com",
    status: status(6.9, 10.4),
    metrics: {
      organicTraffic: { current: 19400, vsLastMonthPct: 6.9, vsLastYearPct: 10.4 },
      totalTraffic: { current: 28600, vsLastMonthPct: 5.8, vsLastYearPct: 8.9 },
      newUsersPct: 64, returningUsersPct: 36,
      bounceRate: 36.4, conversionRate: 3.6, roomNights: 584, revenue: 167200,
    },
    competitorDomains: ["nhow-amsterdam.com", "w-amsterdam.com", "citizen-m.com"],
    keywords: [
      kw("zbh-ams-1", "business hotel amsterdam airport", 12100, 6, 9, "/rooms/business", [["nhow-amsterdam.com", 2], ["w-amsterdam.com", 5], ["citizen-m.com", 8]]),
      kw("zbh-ams-2", "zenith amsterdam hotel", 1900, 1, 1, "/", [["nhow-amsterdam.com", null], ["w-amsterdam.com", null], ["citizen-m.com", null]]),
      kw("zbh-ams-3", "schiphol hotel with conference room", 8100, 4, 7, "/meetings", [["nhow-amsterdam.com", 1], ["w-amsterdam.com", 4], ["citizen-m.com", 7]]),
      kw("zbh-ams-4", "amsterdam hotel near airport cheap", 18100, 11, 15, "/offers", [["nhow-amsterdam.com", 3], ["w-amsterdam.com", 7], ["citizen-m.com", 11]]),
      kw("zbh-ams-5", "amsterdam executive hotel", 6600, 8, 12, "/executive", [["nhow-amsterdam.com", 2], ["w-amsterdam.com", 6], ["citizen-m.com", 9]]),
      kw("zbh-ams-6", "amsterdam hotel city center canal", 22200, 18, 23, "/location", [["nhow-amsterdam.com", 4], ["w-amsterdam.com", 9], ["citizen-m.com", 14]]),
      kw("zbh-ams-7", "netherlands business travel hotel", 9900, 14, 18, "/business", [["nhow-amsterdam.com", 5], ["w-amsterdam.com", 10], ["citizen-m.com", 15]]),
      kw("zbh-ams-8", "amsterdam hotel book online", 27100, 21, 26, "/book", [["nhow-amsterdam.com", 6], ["w-amsterdam.com", 12], ["citizen-m.com", 18]]),
    ],
  },
  {
    id: "zbh-frankfurt",
    chainId: "zenith",
    name: "Zenith Frankfurt Messe",
    location: "Frankfurt, Germany",
    gaPropertyId: "GA4-ZBH-002",
    website: "zenith-frankfurt.com",
    status: status(4.2, 7.6),
    metrics: {
      organicTraffic: { current: 16200, vsLastMonthPct: 4.2, vsLastYearPct: 7.6 },
      totalTraffic: { current: 23800, vsLastMonthPct: 3.6, vsLastYearPct: 6.2 },
      newUsersPct: 58, returningUsersPct: 42,
      bounceRate: 34.7, conversionRate: 4.1, roomNights: 496, revenue: 148800,
    },
    competitorDomains: ["marriott-frankfurt.com", "hilton-frankfurt.com", "steigenberger-frankfurt.com"],
    keywords: [
      kw("zbh-fra-1", "business hotel frankfurt messe", 9900, 5, 8, "/rooms/business", [["marriott-frankfurt.com", 2], ["hilton-frankfurt.com", 4], ["steigenberger-frankfurt.com", 7]]),
      kw("zbh-fra-2", "zenith frankfurt hotel", 1600, 1, 1, "/", [["marriott-frankfurt.com", null], ["hilton-frankfurt.com", null], ["steigenberger-frankfurt.com", null]]),
      kw("zbh-fra-3", "frankfurt trade fair hotel", 12100, 7, 11, "/meetings/tradeshows", [["marriott-frankfurt.com", 1], ["hilton-frankfurt.com", 5], ["steigenberger-frankfurt.com", 8]]),
      kw("zbh-fra-4", "hotel near frankfurt airport", 18100, 13, 17, "/location", [["marriott-frankfurt.com", 3], ["hilton-frankfurt.com", 7], ["steigenberger-frankfurt.com", 12]]),
      kw("zbh-fra-5", "frankfurt executive lounge hotel", 5400, 9, 13, "/executive", [["marriott-frankfurt.com", 2], ["hilton-frankfurt.com", 6], ["steigenberger-frankfurt.com", 10]]),
      kw("zbh-fra-6", "frankfurt hotel conference facilities", 7200, 6, 9, "/meetings", [["marriott-frankfurt.com", 1], ["hilton-frankfurt.com", 4], ["steigenberger-frankfurt.com", 8]]),
      kw("zbh-fra-7", "germany business travel hotel deal", 14800, 17, 22, "/offers", [["marriott-frankfurt.com", 5], ["hilton-frankfurt.com", 9], ["steigenberger-frankfurt.com", 14]]),
      kw("zbh-fra-8", "book frankfurt hotel direct rate", 12100, 22, 27, "/book", [["marriott-frankfurt.com", 6], ["hilton-frankfurt.com", 11], ["steigenberger-frankfurt.com", 16]]),
    ],
  },
  {
    id: "zbh-chicago",
    chainId: "zenith",
    name: "Zenith Chicago Loop",
    location: "Chicago, USA",
    gaPropertyId: "GA4-ZBH-003",
    website: "zenith-chicago.com",
    status: status(-4.8, -3.2),
    metrics: {
      organicTraffic: { current: 21800, vsLastMonthPct: -4.8, vsLastYearPct: -3.2 },
      totalTraffic: { current: 31400, vsLastMonthPct: -3.9, vsLastYearPct: -2.4 },
      newUsersPct: 62, returningUsersPct: 38,
      bounceRate: 38.9, conversionRate: 3.2, roomNights: 528, revenue: 162800,
    },
    competitorDomains: ["theriviera-chicago.com", "peninsula-chicago.com", "chicago-marriott.com"],
    keywords: [
      kw("zbh-chi-1", "business hotel chicago loop downtown", 12100, 9, 11, "/rooms/business", [["theriviera-chicago.com", 3], ["peninsula-chicago.com", 5], ["chicago-marriott.com", 8]]),
      kw("zbh-chi-2", "zenith chicago hotel", 1900, 1, 1, "/", [["theriviera-chicago.com", null], ["peninsula-chicago.com", null], ["chicago-marriott.com", null]]),
      kw("zbh-chi-3", "chicago corporate hotel conference", 9900, 7, 9, "/meetings", [["theriviera-chicago.com", 2], ["peninsula-chicago.com", 4], ["chicago-marriott.com", 7]]),
      kw("zbh-chi-4", "chicago hotel near o'hare airport", 14800, 16, 18, "/location", [["theriviera-chicago.com", 5], ["peninsula-chicago.com", 9], ["chicago-marriott.com", 13]]),
      kw("zbh-chi-5", "chicago hotel deal last minute", 22200, 28, 24, "/offers", [["theriviera-chicago.com", 7], ["peninsula-chicago.com", 12], ["chicago-marriott.com", 18]]),
      kw("zbh-chi-6", "chicago loop hotel walk to lakefront", 8100, 12, 14, "/location", [["theriviera-chicago.com", 4], ["peninsula-chicago.com", 7], ["chicago-marriott.com", 11]]),
      kw("zbh-chi-7", "chicago executive hotel fitness center", 6600, 14, 17, "/amenities", [["theriviera-chicago.com", 5], ["peninsula-chicago.com", 9], ["chicago-marriott.com", 14]]),
      kw("zbh-chi-8", "book chicago hotel best rate direct", 18100, 29, 25, "/book", [["theriviera-chicago.com", 8], ["peninsula-chicago.com", 14], ["chicago-marriott.com", 19]]),
    ],
  },
  {
    id: "zbh-singapore",
    chainId: "zenith",
    name: "Zenith Singapore Marina Bay",
    location: "Singapore",
    gaPropertyId: "GA4-ZBH-004",
    website: "zenith-singapore.com",
    status: status(9.8, 13.6),
    metrics: {
      organicTraffic: { current: 24600, vsLastMonthPct: 9.8, vsLastYearPct: 13.6 },
      totalTraffic: { current: 34800, vsLastMonthPct: 8.2, vsLastYearPct: 11.4 },
      newUsersPct: 61, returningUsersPct: 39,
      bounceRate: 32.8, conversionRate: 4.4, roomNights: 682, revenue: 218400,
    },
    competitorDomains: ["raffles-sg.com", "fullerton-sg.com", "marina-bay-sands.com"],
    keywords: [
      kw("zbh-sg-1", "business hotel singapore marina bay", 12100, 5, 8, "/rooms/business", [["raffles-sg.com", 2], ["fullerton-sg.com", 4], ["marina-bay-sands.com", 7]]),
      kw("zbh-sg-2", "zenith singapore hotel", 2100, 1, 1, "/", [["raffles-sg.com", null], ["fullerton-sg.com", null], ["marina-bay-sands.com", null]]),
      kw("zbh-sg-3", "singapore corporate meeting hotel", 9900, 4, 7, "/meetings", [["raffles-sg.com", 1], ["fullerton-sg.com", 3], ["marina-bay-sands.com", 6]]),
      kw("zbh-sg-4", "singapore hotel conference facilities", 8100, 6, 10, "/meetings/events", [["raffles-sg.com", 2], ["fullerton-sg.com", 5], ["marina-bay-sands.com", 8]]),
      kw("zbh-sg-5", "cbd hotel singapore business district", 14800, 9, 13, "/location", [["raffles-sg.com", 3], ["fullerton-sg.com", 6], ["marina-bay-sands.com", 11]]),
      kw("zbh-sg-6", "singapore hotel deal direct booking", 22200, 14, 19, "/offers", [["raffles-sg.com", 5], ["fullerton-sg.com", 9], ["marina-bay-sands.com", 14]]),
      kw("zbh-sg-7", "singapore executive lounge hotel", 6600, 11, 15, "/executive", [["raffles-sg.com", 4], ["fullerton-sg.com", 7], ["marina-bay-sands.com", 12]]),
      kw("zbh-sg-8", "book singapore hotel marina bay view", 18100, 18, 23, "/book", [["raffles-sg.com", 6], ["fullerton-sg.com", 10], ["marina-bay-sands.com", 15]]),
    ],
  },
  {
    id: "zbh-toronto",
    chainId: "zenith",
    name: "Zenith Toronto Bay Street",
    location: "Toronto, Canada",
    gaPropertyId: "GA4-ZBH-005",
    website: "zenith-toronto.com",
    status: status(1.8, -6.4),
    metrics: {
      organicTraffic: { current: 14800, vsLastMonthPct: 1.8, vsLastYearPct: -6.4 },
      totalTraffic: { current: 21200, vsLastMonthPct: 1.4, vsLastYearPct: -5.1 },
      newUsersPct: 60, returningUsersPct: 40,
      bounceRate: 40.2, conversionRate: 3.1, roomNights: 412, revenue: 124600,
    },
    competitorDomains: ["ritzcarlton-toronto.com", "shangri-la-toronto.com", "fairmont-royal-york.com"],
    keywords: [
      kw("zbh-tor-1", "business hotel toronto bay street", 8100, 10, 13, "/rooms/business", [["ritzcarlton-toronto.com", 2], ["shangri-la-toronto.com", 5], ["fairmont-royal-york.com", 8]]),
      kw("zbh-tor-2", "zenith toronto hotel", 1300, 1, 1, "/", [["ritzcarlton-toronto.com", null], ["shangri-la-toronto.com", null], ["fairmont-royal-york.com", null]]),
      kw("zbh-tor-3", "toronto downtown hotel corporate rate", 12100, 14, 18, "/corporate", [["ritzcarlton-toronto.com", 3], ["shangri-la-toronto.com", 7], ["fairmont-royal-york.com", 11]]),
      kw("zbh-tor-4", "toronto hotel near financial district", 9900, 12, 16, "/location", [["ritzcarlton-toronto.com", 4], ["shangri-la-toronto.com", 8], ["fairmont-royal-york.com", 12]]),
      kw("zbh-tor-5", "toronto conference hotel meetings", 7200, 8, 12, "/meetings", [["ritzcarlton-toronto.com", 2], ["shangri-la-toronto.com", 6], ["fairmont-royal-york.com", 9]]),
      kw("zbh-tor-6", "toronto hotel deal weekend", 14800, 22, 26, "/offers", [["ritzcarlton-toronto.com", 6], ["shangri-la-toronto.com", 11], ["fairmont-royal-york.com", 16]]),
      kw("zbh-tor-7", "toronto hotel cn tower view", 6600, 19, 24, "/rooms/cityview", [["ritzcarlton-toronto.com", 5], ["shangri-la-toronto.com", 9], ["fairmont-royal-york.com", 14]]),
      kw("zbh-tor-8", "book toronto hotel best rate", 18100, 27, 32, "/book", [["ritzcarlton-toronto.com", 7], ["shangri-la-toronto.com", 12], ["fairmont-royal-york.com", 18]]),
    ],
  },
];

// ─── CHAIN 5: Harbour Boutique Hotels ────────────────────────────────────────
const harbourProperties: Property[] = [
  {
    id: "hbh-edinburgh",
    chainId: "harbour",
    name: "Harbour Edinburgh Old Town",
    location: "Edinburgh, Scotland",
    gaPropertyId: "GA4-HBH-001",
    website: "harbour-edinburgh.com",
    status: status(12.3, 17.8),
    metrics: {
      organicTraffic: { current: 11200, vsLastMonthPct: 12.3, vsLastYearPct: 17.8 },
      totalTraffic: { current: 16100, vsLastMonthPct: 10.4, vsLastYearPct: 14.9 },
      newUsersPct: 71, returningUsersPct: 29,
      bounceRate: 41.3, conversionRate: 3.4, roomNights: 264, revenue: 84800,
    },
    competitorDomains: ["the-witchery.com", "hotel-missoni-edinburgh.com", "balmoral-hotel.com"],
    keywords: [
      kw("hbh-edi-1", "boutique hotel edinburgh old town", 8100, 5, 8, "/rooms", [["the-witchery.com", 2], ["hotel-missoni-edinburgh.com", 4], ["balmoral-hotel.com", 7]]),
      kw("hbh-edi-2", "harbour edinburgh hotel", 1100, 1, 1, "/", [["the-witchery.com", null], ["hotel-missoni-edinburgh.com", null], ["balmoral-hotel.com", null]]),
      kw("hbh-edi-3", "edinburgh castle view hotel", 12100, 7, 10, "/rooms/castleview", [["the-witchery.com", 2], ["hotel-missoni-edinburgh.com", 5], ["balmoral-hotel.com", 9]]),
      kw("hbh-edi-4", "scotland boutique hotel deal", 9900, 9, 13, "/offers", [["the-witchery.com", 3], ["hotel-missoni-edinburgh.com", 6], ["balmoral-hotel.com", 10]]),
      kw("hbh-edi-5", "edinburgh fringe festival hotel", 7200, 11, 15, "/packages/fringe", [["the-witchery.com", 4], ["hotel-missoni-edinburgh.com", 7], ["balmoral-hotel.com", 12]]),
      kw("hbh-edi-6", "royal mile hotel edinburgh", 14800, 14, 18, "/location", [["the-witchery.com", 5], ["hotel-missoni-edinburgh.com", 9], ["balmoral-hotel.com", 14]]),
      kw("hbh-edi-7", "edinburgh hotel whisky bar", 5400, 8, 12, "/dining", [["the-witchery.com", 2], ["hotel-missoni-edinburgh.com", 5], ["balmoral-hotel.com", 8]]),
      kw("hbh-edi-8", "book edinburgh boutique hotel", 9900, 16, 21, "/book", [["the-witchery.com", 6], ["hotel-missoni-edinburgh.com", 10], ["balmoral-hotel.com", 15]]),
    ],
  },
  {
    id: "hbh-lisbon",
    chainId: "harbour",
    name: "Harbour Lisbon Alfama",
    location: "Lisbon, Portugal",
    gaPropertyId: "GA4-HBH-002",
    website: "harbour-lisbon.com",
    status: status(-16.8, -21.4),
    metrics: {
      organicTraffic: { current: 7800, vsLastMonthPct: -16.8, vsLastYearPct: -21.4 },
      totalTraffic: { current: 11200, vsLastMonthPct: -13.4, vsLastYearPct: -17.9 },
      newUsersPct: 74, returningUsersPct: 26,
      bounceRate: 58.6, conversionRate: 1.3, roomNights: 112, revenue: 34200,
    },
    competitorDomains: ["bairro-alto-hotel.com", "palacio-belmonte.com", "casa-do-principe.com"],
    keywords: [
      kw("hbh-lis-1", "boutique hotel lisbon alfama", 6600, 24, 16, "/rooms", [["bairro-alto-hotel.com", 2], ["palacio-belmonte.com", 5], ["casa-do-principe.com", 9]]),
      kw("hbh-lis-2", "harbour lisbon hotel", 880, 1, 1, "/", [["bairro-alto-hotel.com", null], ["palacio-belmonte.com", null], ["casa-do-principe.com", null]]),
      kw("hbh-lis-3", "lisbon historic district hotel", 8100, 31, 22, "/location", [["bairro-alto-hotel.com", 3], ["palacio-belmonte.com", 7], ["casa-do-principe.com", 12]]),
      kw("hbh-lis-4", "lisbon fado music hotel", 5400, 27, 19, "/experiences", [["bairro-alto-hotel.com", 4], ["palacio-belmonte.com", 8], ["casa-do-principe.com", 14]]),
      kw("hbh-lis-5", "portugal boutique hotel deal", 9900, 38, 27, "/offers", [["bairro-alto-hotel.com", 6], ["palacio-belmonte.com", 11], ["casa-do-principe.com", 17]]),
      kw("hbh-lis-6", "lisbon hotel tram tour", 7200, 22, 15, "/activities", [["bairro-alto-hotel.com", 3], ["palacio-belmonte.com", 7], ["casa-do-principe.com", 11]]),
      kw("hbh-lis-7", "lisbon ocean view boutique hotel", 4400, 34, 24, "/rooms/seaview", [["bairro-alto-hotel.com", 5], ["palacio-belmonte.com", 10], ["casa-do-principe.com", 16]]),
      kw("hbh-lis-8", "book lisbon boutique hotel cheap", 12100, 45, 33, "/book", [["bairro-alto-hotel.com", 8], ["palacio-belmonte.com", 14], ["casa-do-principe.com", 21]]),
    ],
  },
  {
    id: "hbh-prague",
    chainId: "harbour",
    name: "Harbour Prague Old Square",
    location: "Prague, Czech Republic",
    gaPropertyId: "GA4-HBH-003",
    website: "harbour-prague.com",
    status: status(3.9, 6.2),
    metrics: {
      organicTraffic: { current: 9600, vsLastMonthPct: 3.9, vsLastYearPct: 6.2 },
      totalTraffic: { current: 14100, vsLastMonthPct: 3.2, vsLastYearPct: 5.1 },
      newUsersPct: 77, returningUsersPct: 23,
      bounceRate: 44.7, conversionRate: 2.8, roomNights: 218, revenue: 61400,
    },
    competitorDomains: ["aria-hotel-prague.com", "four-seasons-prague.com", "hotel-josef.com"],
    keywords: [
      kw("hbh-pra-1", "boutique hotel prague old town", 9900, 8, 11, "/rooms", [["aria-hotel-prague.com", 2], ["four-seasons-prague.com", 4], ["hotel-josef.com", 7]]),
      kw("hbh-pra-2", "harbour prague boutique hotel", 1100, 1, 1, "/", [["aria-hotel-prague.com", null], ["four-seasons-prague.com", null], ["hotel-josef.com", null]]),
      kw("hbh-pra-3", "prague castle view hotel", 7200, 11, 14, "/rooms/castleview", [["aria-hotel-prague.com", 3], ["four-seasons-prague.com", 5], ["hotel-josef.com", 9]]),
      kw("hbh-pra-4", "czech republic boutique hotel deal", 6600, 14, 18, "/offers", [["aria-hotel-prague.com", 4], ["four-seasons-prague.com", 7], ["hotel-josef.com", 12]]),
      kw("hbh-pra-5", "prague hotel charles bridge walk", 8100, 12, 16, "/location", [["aria-hotel-prague.com", 3], ["four-seasons-prague.com", 6], ["hotel-josef.com", 10]]),
      kw("hbh-pra-6", "prague hotel jazz bar live music", 4400, 9, 13, "/dining", [["aria-hotel-prague.com", 2], ["four-seasons-prague.com", 5], ["hotel-josef.com", 8]]),
      kw("hbh-pra-7", "europe boutique hotel weekend break", 12100, 19, 24, "/packages", [["aria-hotel-prague.com", 6], ["four-seasons-prague.com", 10], ["hotel-josef.com", 15]]),
      kw("hbh-pra-8", "book prague boutique hotel online", 14800, 23, 28, "/book", [["aria-hotel-prague.com", 7], ["four-seasons-prague.com", 11], ["hotel-josef.com", 17]]),
    ],
  },
  {
    id: "hbh-barcelona",
    chainId: "harbour",
    name: "Harbour Barcelona Gothic Quarter",
    location: "Barcelona, Spain",
    gaPropertyId: "GA4-HBH-004",
    website: "harbour-barcelona.com",
    status: status(7.6, 11.4),
    metrics: {
      organicTraffic: { current: 14200, vsLastMonthPct: 7.6, vsLastYearPct: 11.4 },
      totalTraffic: { current: 20400, vsLastMonthPct: 6.4, vsLastYearPct: 9.8 },
      newUsersPct: 73, returningUsersPct: 27,
      bounceRate: 40.1, conversionRate: 3.1, roomNights: 328, revenue: 98400,
    },
    competitorDomains: ["hotel-arts-barcelona.com", "w-barcelona.com", "grand-hotel-central.com"],
    keywords: [
      kw("hbh-bar-1", "boutique hotel barcelona gothic quarter", 12100, 7, 10, "/rooms", [["hotel-arts-barcelona.com", 2], ["w-barcelona.com", 5], ["grand-hotel-central.com", 8]]),
      kw("hbh-bar-2", "harbour barcelona hotel", 1600, 1, 1, "/", [["hotel-arts-barcelona.com", null], ["w-barcelona.com", null], ["grand-hotel-central.com", null]]),
      kw("hbh-bar-3", "barcelona hotel near sagrada familia", 14800, 9, 13, "/location", [["hotel-arts-barcelona.com", 3], ["w-barcelona.com", 6], ["grand-hotel-central.com", 10]]),
      kw("hbh-bar-4", "spain boutique hotel deal", 9900, 12, 16, "/offers", [["hotel-arts-barcelona.com", 4], ["w-barcelona.com", 7], ["grand-hotel-central.com", 11]]),
      kw("hbh-bar-5", "barcelona hotel rooftop pool", 8100, 8, 12, "/amenities", [["hotel-arts-barcelona.com", 2], ["w-barcelona.com", 5], ["grand-hotel-central.com", 9]]),
      kw("hbh-bar-6", "barcelona hotel las ramblas walkable", 18100, 16, 21, "/location", [["hotel-arts-barcelona.com", 5], ["w-barcelona.com", 9], ["grand-hotel-central.com", 14]]),
      kw("hbh-bar-7", "barcelona food tour hotel package", 6600, 11, 15, "/experiences", [["hotel-arts-barcelona.com", 3], ["w-barcelona.com", 7], ["grand-hotel-central.com", 12]]),
      kw("hbh-bar-8", "book barcelona boutique hotel direct", 12100, 19, 24, "/book", [["hotel-arts-barcelona.com", 6], ["w-barcelona.com", 11], ["grand-hotel-central.com", 16]]),
    ],
  },
  {
    id: "hbh-amsterdam",
    chainId: "harbour",
    name: "Harbour Amsterdam Canal House",
    location: "Amsterdam, Netherlands",
    gaPropertyId: "GA4-HBH-005",
    website: "harbour-amsterdam.com",
    status: status(-5.2, -8.1),
    metrics: {
      organicTraffic: { current: 8900, vsLastMonthPct: -5.2, vsLastYearPct: -8.1 },
      totalTraffic: { current: 12800, vsLastMonthPct: -4.1, vsLastYearPct: -6.4 },
      newUsersPct: 69, returningUsersPct: 31,
      bounceRate: 47.9, conversionRate: 2.4, roomNights: 196, revenue: 62800,
    },
    competitorDomains: ["pulitzer-amsterdam.com", "seven-one-seven.com", "andaz-amsterdam.com"],
    keywords: [
      kw("hbh-ada-1", "boutique hotel amsterdam canal house", 8100, 13, 10, "/rooms", [["pulitzer-amsterdam.com", 2], ["seven-one-seven.com", 5], ["andaz-amsterdam.com", 8]]),
      kw("hbh-ada-2", "harbour amsterdam canal hotel", 1100, 1, 1, "/", [["pulitzer-amsterdam.com", null], ["seven-one-seven.com", null], ["andaz-amsterdam.com", null]]),
      kw("hbh-ada-3", "amsterdam historic canal hotel", 9900, 16, 13, "/location", [["pulitzer-amsterdam.com", 3], ["seven-one-seven.com", 6], ["andaz-amsterdam.com", 10]]),
      kw("hbh-ada-4", "netherlands boutique hotel deal", 7200, 21, 17, "/offers", [["pulitzer-amsterdam.com", 5], ["seven-one-seven.com", 9], ["andaz-amsterdam.com", 14]]),
      kw("hbh-ada-5", "amsterdam hotel bike rental included", 6600, 9, 7, "/amenities", [["pulitzer-amsterdam.com", 3], ["seven-one-seven.com", 7], ["andaz-amsterdam.com", 11]]),
      kw("hbh-ada-6", "amsterdam museum hotel deal", 12100, 18, 15, "/packages/museum", [["pulitzer-amsterdam.com", 4], ["seven-one-seven.com", 8], ["andaz-amsterdam.com", 13]]),
      kw("hbh-ada-7", "amsterdam hotel jordaan neighbourhood", 9900, 14, 11, "/location", [["pulitzer-amsterdam.com", 3], ["seven-one-seven.com", 6], ["andaz-amsterdam.com", 10]]),
      kw("hbh-ada-8", "book amsterdam boutique hotel", 14800, 26, 22, "/book", [["pulitzer-amsterdam.com", 7], ["seven-one-seven.com", 12], ["andaz-amsterdam.com", 17]]),
    ],
  },
];

// ─── Compute chain metrics from properties ────────────────────────────────────
function computeChainMetrics(properties: Property[]) {
  const n = properties.length;
  const totOrgCur = properties.reduce((s, p) => s + p.metrics.organicTraffic.current, 0);
  const totOrgLM = properties.reduce((s, p) => s + (p.metrics.organicTraffic.current / (1 + p.metrics.organicTraffic.vsLastMonthPct / 100)), 0);
  const totOrgLY = properties.reduce((s, p) => s + (p.metrics.organicTraffic.current / (1 + p.metrics.organicTraffic.vsLastYearPct / 100)), 0);
  const totTotCur = properties.reduce((s, p) => s + p.metrics.totalTraffic.current, 0);
  const totTotLM = properties.reduce((s, p) => s + (p.metrics.totalTraffic.current / (1 + p.metrics.totalTraffic.vsLastMonthPct / 100)), 0);
  const totTotLY = properties.reduce((s, p) => s + (p.metrics.totalTraffic.current / (1 + p.metrics.totalTraffic.vsLastYearPct / 100)), 0);
  return {
    organicTraffic: {
      current: totOrgCur,
      vsLastMonthPct: Math.round(((totOrgCur - totOrgLM) / totOrgLM) * 1000) / 10,
      vsLastYearPct: Math.round(((totOrgCur - totOrgLY) / totOrgLY) * 1000) / 10,
    },
    totalTraffic: {
      current: totTotCur,
      vsLastMonthPct: Math.round(((totTotCur - totTotLM) / totTotLM) * 1000) / 10,
      vsLastYearPct: Math.round(((totTotCur - totTotLY) / totTotLY) * 1000) / 10,
    },
    avgBounceRate: Math.round((properties.reduce((s, p) => s + p.metrics.bounceRate, 0) / n) * 10) / 10,
    avgConversionRate: Math.round((properties.reduce((s, p) => s + p.metrics.conversionRate, 0) / n) * 10) / 10,
    totalRoomNights: properties.reduce((s, p) => s + p.metrics.roomNights, 0),
    totalRevenue: properties.reduce((s, p) => s + p.metrics.revenue, 0),
    avgNewUsersPct: Math.round(properties.reduce((s, p) => s + p.metrics.newUsersPct, 0) / n),
    criticalCount: properties.filter((p) => p.status === "critical").length,
    warningCount: properties.filter((p) => p.status === "warning").length,
    healthyCount: properties.filter((p) => p.status === "healthy").length,
  };
}

// ─── Chains ──────────────────────────────────────────────────────────────────
export const chains: Chain[] = [
  {
    id: "meridian",
    name: "Meridian Luxury Hotels",
    shortName: "Meridian",
    color: "indigo",
    bgColor: "bg-indigo-600",
    properties: meridianProperties,
    metrics: computeChainMetrics(meridianProperties),
  },
  {
    id: "crestview",
    name: "Crestview Resorts",
    shortName: "Crestview",
    color: "emerald",
    bgColor: "bg-emerald-600",
    properties: crestviewProperties,
    metrics: computeChainMetrics(crestviewProperties),
  },
  {
    id: "heritage",
    name: "Heritage Palace Hotels",
    shortName: "Heritage",
    color: "amber",
    bgColor: "bg-amber-600",
    properties: heritageProperties,
    metrics: computeChainMetrics(heritageProperties),
  },
  {
    id: "zenith",
    name: "Zenith Business Hotels",
    shortName: "Zenith",
    color: "purple",
    bgColor: "bg-purple-600",
    properties: zenithProperties,
    metrics: computeChainMetrics(zenithProperties),
  },
  {
    id: "harbour",
    name: "Harbour Boutique Hotels",
    shortName: "Harbour",
    color: "cyan",
    bgColor: "bg-cyan-600",
    properties: harbourProperties,
    metrics: computeChainMetrics(harbourProperties),
  },
];

export function getChain(id: string): Chain | undefined {
  return chains.find((c) => c.id === id);
}

export function getProperty(chainId: string, propertyId: string) {
  return getChain(chainId)?.properties.find((p) => p.id === propertyId);
}

export function getAllCriticalProperties() {
  return chains.flatMap((c) =>
    c.properties
      .filter((p) => p.status === "critical")
      .map((p) => ({ ...p, chainName: c.name, chainId: c.id }))
  );
}

export function getAllWarningProperties() {
  return chains.flatMap((c) =>
    c.properties
      .filter((p) => p.status === "warning")
      .map((p) => ({ ...p, chainName: c.name, chainId: c.id }))
  );
}
