-- Seed data for Analytics Central Dashboard
-- Run after schema.sql. Safe to re-run (ON CONFLICT DO NOTHING).

-- ── Chains ───────────────────────────────────────────────────────────────────
INSERT INTO chains (id, name, short_name, color, bg_color) VALUES
  ('meridian',  'Meridian Luxury Hotels',    'Meridian',  'indigo',  'bg-indigo-600'),
  ('crestview', 'Crestview Resorts',         'Crestview', 'emerald', 'bg-emerald-600'),
  ('heritage',  'Heritage Palace Hotels',    'Heritage',  'amber',   'bg-amber-600'),
  ('zenith',    'Zenith Business Hotels',    'Zenith',    'purple',  'bg-purple-600'),
  ('harbour',   'Harbour Boutique Hotels',   'Harbour',   'cyan',    'bg-cyan-600')
ON CONFLICT DO NOTHING;

-- ── Properties ───────────────────────────────────────────────────────────────
INSERT INTO properties (id, chain_id, name, location, ga_property_id, website) VALUES
  ('mrd-london',    'meridian',  'Meridian London Hyde Park',         'London, UK',             'GA4-MRD-001', 'meridian-london.com'),
  ('mrd-paris',     'meridian',  'Meridian Paris Champs-Élysées',     'Paris, France',          'GA4-MRD-002', 'meridian-paris.com'),
  ('mrd-dubai',     'meridian',  'Meridian Dubai Marina',             'Dubai, UAE',             'GA4-MRD-003', 'meridian-dubai.com'),
  ('mrd-ny',        'meridian',  'Meridian New York Midtown',         'New York, USA',          'GA4-MRD-004', 'meridian-newyork.com'),
  ('mrd-singapore', 'meridian',  'Meridian Singapore Orchard',        'Singapore',              'GA4-MRD-005', 'meridian-singapore.com'),
  ('mrd-rome',      'meridian',  'Meridian Rome Colosseum View',      'Rome, Italy',            'GA4-MRD-006', 'meridian-rome.com'),
  ('mrd-tokyo',     'meridian',  'Meridian Tokyo Shinjuku',           'Tokyo, Japan',           'GA4-MRD-007', 'meridian-tokyo.com'),
  ('mrd-sydney',    'meridian',  'Meridian Sydney Harbour',           'Sydney, Australia',      'GA4-MRD-008', 'meridian-sydney.com'),
  ('crv-maldives',  'crestview', 'Crestview Maldives Overwater',      'Maldives',               'GA4-CRV-001', 'crestview-maldives.com'),
  ('crv-bali',      'crestview', 'Crestview Bali Ubud Retreat',       'Bali, Indonesia',        'GA4-CRV-002', 'crestview-bali.com'),
  ('crv-phuket',    'crestview', 'Crestview Phuket Beachfront',       'Phuket, Thailand',       'GA4-CRV-003', 'crestview-phuket.com'),
  ('crv-cancun',    'crestview', 'Crestview Cancún Ocean View',       'Cancún, Mexico',         'GA4-CRV-004', 'crestview-cancun.com'),
  ('crv-santorini', 'crestview', 'Crestview Santorini Caldera',       'Santorini, Greece',      'GA4-CRV-005', 'crestview-santorini.com'),
  ('crv-abudhabi',  'crestview', 'Crestview Abu Dhabi Corniche',      'Abu Dhabi, UAE',         'GA4-CRV-006', 'crestview-abudhabi.com'),
  ('hph-jaipur',    'heritage',  'Heritage Palace Jaipur',            'Jaipur, India',          'GA4-HPH-001', 'heritage-jaipur.com'),
  ('hph-udaipur',   'heritage',  'Heritage Palace Udaipur Lake',      'Udaipur, India',         'GA4-HPH-002', 'heritage-udaipur.com'),
  ('hph-agra',      'heritage',  'Heritage Palace Agra Taj View',     'Agra, India',            'GA4-HPH-003', 'heritage-agra.com'),
  ('hph-jodhpur',   'heritage',  'Heritage Palace Jodhpur Blue City', 'Jodhpur, India',         'GA4-HPH-004', 'heritage-jodhpur.com'),
  ('hph-mysore',    'heritage',  'Heritage Palace Mysore',            'Mysore, India',          'GA4-HPH-005', 'heritage-mysore.com'),
  ('zbh-amsterdam', 'zenith',    'Zenith Amsterdam Schiphol',         'Amsterdam, Netherlands', 'GA4-ZBH-001', 'zenith-amsterdam.com'),
  ('zbh-frankfurt', 'zenith',    'Zenith Frankfurt Messe',            'Frankfurt, Germany',     'GA4-ZBH-002', 'zenith-frankfurt.com'),
  ('zbh-chicago',   'zenith',    'Zenith Chicago Loop',               'Chicago, USA',           'GA4-ZBH-003', 'zenith-chicago.com'),
  ('zbh-singapore', 'zenith',    'Zenith Singapore Marina Bay',       'Singapore',              'GA4-ZBH-004', 'zenith-singapore.com'),
  ('zbh-toronto',   'zenith',    'Zenith Toronto Bay Street',         'Toronto, Canada',        'GA4-ZBH-005', 'zenith-toronto.com'),
  ('hbh-edinburgh', 'harbour',   'Harbour Edinburgh Old Town',        'Edinburgh, Scotland',    'GA4-HBH-001', 'harbour-edinburgh.com'),
  ('hbh-lisbon',    'harbour',   'Harbour Lisbon Alfama',             'Lisbon, Portugal',       'GA4-HBH-002', 'harbour-lisbon.com'),
  ('hbh-prague',    'harbour',   'Harbour Prague Old Square',         'Prague, Czech Republic', 'GA4-HBH-003', 'harbour-prague.com'),
  ('hbh-barcelona', 'harbour',   'Harbour Barcelona Gothic Quarter',  'Barcelona, Spain',       'GA4-HBH-004', 'harbour-barcelona.com'),
  ('hbh-amsterdam', 'harbour',   'Harbour Amsterdam Canal House',     'Amsterdam, Netherlands', 'GA4-HBH-005', 'harbour-amsterdam.com')
ON CONFLICT DO NOTHING;

-- ── Property Metrics ─────────────────────────────────────────────────────────
INSERT INTO property_metrics
  (property_id, recorded_at,
   organic_traffic_current, organic_vs_last_month_pct, organic_vs_last_year_pct,
   total_traffic_current,   total_vs_last_month_pct,   total_vs_last_year_pct,
   new_users_pct, returning_users_pct, bounce_rate, conversion_rate, room_nights, revenue)
VALUES
  ('mrd-london',    CURRENT_DATE, 12450, -18.3, -24.1, 18920, -14.2, -19.8, 68, 32, 54.2, 1.8,  284,  89500),
  ('mrd-paris',     CURRENT_DATE, 18730,  -6.1,  -9.4, 26800,  -4.3,  -7.1, 72, 28, 48.6, 2.4,  412, 143200),
  ('mrd-dubai',     CURRENT_DATE, 24100,   9.2,  14.6, 33400,   7.8,  12.1, 81, 19, 41.3, 3.1,  628, 218400),
  ('mrd-ny',        CURRENT_DATE, 31200,   4.1,   6.8, 44800,   3.2,   5.4, 75, 25, 43.8, 2.8,  742, 267100),
  ('mrd-singapore', CURRENT_DATE, 16800,  -2.1,   3.4, 23100,  -1.4,   2.8, 70, 30, 46.1, 2.2,  398, 134600),
  ('mrd-rome',      CURRENT_DATE,  8320, -22.7, -31.4, 11900, -19.1, -27.3, 74, 26, 61.8, 1.1,  121,  38200),
  ('mrd-tokyo',     CURRENT_DATE, 21400,  11.8,  18.3, 29800,   9.4,  15.7, 83, 17, 38.4, 3.4,  561, 196700),
  ('mrd-sydney',    CURRENT_DATE, 14900,   1.3,  -4.2, 21300,   0.9,  -3.1, 69, 31, 45.7, 2.1,  337, 118400),
  ('crv-maldives',  CURRENT_DATE, 28900,  16.4,  22.8, 38400,  14.1,  19.6, 88, 12, 32.1, 4.2,  814, 368200),
  ('crv-bali',      CURRENT_DATE, 19200, -13.6, -19.8, 26700, -11.2, -16.4, 77, 23, 51.4, 2.0,  298,  94800),
  ('crv-phuket',    CURRENT_DATE, 22100,   5.8,   8.4, 31400,   4.6,   6.9, 79, 21, 39.7, 3.3,  524, 164200),
  ('crv-cancun',    CURRENT_DATE, 17800,  -7.4, -11.2, 25200,  -5.8,  -9.1, 82, 18, 49.3, 2.4,  386, 123400),
  ('crv-santorini', CURRENT_DATE, 16400,   8.1,  12.6, 22800,   6.9,  10.4, 76, 24, 37.2, 3.8,  438, 197800),
  ('crv-abudhabi',  CURRENT_DATE, 13400,   3.2,  -5.8, 19100,   2.6,  -4.3, 73, 27, 44.8, 2.7,  318, 112600),
  ('hph-jaipur',    CURRENT_DATE,  6840, -25.3, -33.7,  9800, -21.4, -29.1, 69, 31, 64.2, 0.9,   78,  24600),
  ('hph-udaipur',   CURRENT_DATE,  9200,  -8.6, -12.4, 13100,  -7.1, -10.2, 71, 29, 55.8, 1.4,  148,  56800),
  ('hph-agra',      CURRENT_DATE, 11800,   7.4,  11.2, 16900,   6.1,   9.3, 73, 27, 43.6, 2.3,  236,  78400),
  ('hph-jodhpur',   CURRENT_DATE,  8400,   2.6,   4.8, 11900,   1.9,   3.6, 68, 32, 47.3, 1.9,  176,  58200),
  ('hph-mysore',    CURRENT_DATE,  7100,  -3.8,   1.4, 10200,  -2.9,   0.9, 65, 35, 50.1, 1.7,  142,  44800),
  ('zbh-amsterdam', CURRENT_DATE, 19400,   6.9,  10.4, 28600,   5.8,   8.9, 64, 36, 36.4, 3.6,  584, 167200),
  ('zbh-frankfurt', CURRENT_DATE, 16200,   4.2,   7.6, 23800,   3.6,   6.2, 58, 42, 34.7, 4.1,  496, 148800),
  ('zbh-chicago',   CURRENT_DATE, 21800,  -4.8,  -3.2, 31400,  -3.9,  -2.4, 62, 38, 38.9, 3.2,  528, 162800),
  ('zbh-singapore', CURRENT_DATE, 24600,   9.8,  13.6, 34800,   8.2,  11.4, 61, 39, 32.8, 4.4,  682, 218400),
  ('zbh-toronto',   CURRENT_DATE, 14800,   1.8,  -6.4, 21200,   1.4,  -5.1, 60, 40, 40.2, 3.1,  412, 124600),
  ('hbh-edinburgh', CURRENT_DATE, 11200,  12.3,  17.8, 16100,  10.4,  14.9, 71, 29, 41.3, 3.4,  264,  84800),
  ('hbh-lisbon',    CURRENT_DATE,  7800, -16.8, -21.4, 11200, -13.4, -17.9, 74, 26, 58.6, 1.3,  112,  34200),
  ('hbh-prague',    CURRENT_DATE,  9600,   3.9,   6.2, 14100,   3.2,   5.1, 77, 23, 44.7, 2.8,  218,  61400),
  ('hbh-barcelona', CURRENT_DATE, 14200,   7.6,  11.4, 20400,   6.4,   9.8, 73, 27, 40.1, 3.1,  328,  98400),
  ('hbh-amsterdam', CURRENT_DATE,  8900,  -5.2,  -8.1, 12800,  -4.1,  -6.4, 69, 31, 47.9, 2.4,  196,  62800)
ON CONFLICT DO NOTHING;

-- ── Competitor Domains ───────────────────────────────────────────────────────
INSERT INTO competitor_domains (property_id, domain) VALUES
  ('mrd-london',    'marriott-london.com'),('mrd-london',    'hilton-london.co.uk'),('mrd-london',    'radisson-hyde.com'),
  ('mrd-paris',     'fourseasons-paris.com'),('mrd-paris',   'ritz-paris.com'),('mrd-paris',        'plaza-athenee.com'),
  ('mrd-dubai',     'address-dubai.com'),('mrd-dubai',       'atlantis-dubai.com'),('mrd-dubai',      'burj-hotel.com'),
  ('mrd-ny',        'plaza-nyc.com'),('mrd-ny',             'waldorf-astoria.com'),('mrd-ny',         'the-mark-hotel.com'),
  ('mrd-singapore', 'marina-bay-sands.com'),('mrd-singapore','raffles-singapore.com'),('mrd-singapore','shangri-la.com'),
  ('mrd-rome',      'hotel-hassler.com'),('mrd-rome',        'de-russie.com'),('mrd-rome',           'hotel-eden-rome.com'),
  ('mrd-tokyo',     'park-hyatt-tokyo.com'),('mrd-tokyo',    'aman-tokyo.com'),('mrd-tokyo',         'peninsula-tokyo.com'),
  ('mrd-sydney',    'park-hyatt-sydney.com'),('mrd-sydney',  'shangri-la-sydney.com'),('mrd-sydney',  'four-seasons-sydney.com'),
  ('crv-maldives',  'soneva-maldives.com'),('crv-maldives',  'gili-lankanfushi.com'),('crv-maldives', 'anantara-maldives.com'),
  ('crv-bali',      'alaya-ubud.com'),('crv-bali',           'como-shambhala.com'),('crv-bali',       'four-seasons-bali.com'),
  ('crv-phuket',    'trisara-phuket.com'),('crv-phuket',     'amanpuri.com'),('crv-phuket',          'como-phuket.com'),
  ('crv-cancun',    'moon-palace.com'),('crv-cancun',        'live-aqua-cancun.com'),('crv-cancun',   'le-blanc-spa.com'),
  ('crv-santorini', 'grace-hotel.com'),('crv-santorini',     'canaves-oia.com'),('crv-santorini',    'andronis-luxury.com'),
  ('crv-abudhabi',  'emirates-palace.com'),('crv-abudhabi',  'rosewood-abu-dhabi.com'),('crv-abudhabi','st-regis-abudhabi.com'),
  ('hph-jaipur',    'taj-rambagh.com'),('hph-jaipur',        'oberoi-rajvilas.com'),('hph-jaipur',    'aman-bagh.com'),
  ('hph-udaipur',   'taj-lake-palace.com'),('hph-udaipur',   'oberoi-udaivilas.com'),('hph-udaipur',  'lebua-udaipur.com'),
  ('hph-agra',      'oberoi-amarvilas.com'),('hph-agra',      'ita-mughal.com'),('hph-agra',          'trident-agra.com'),
  ('hph-jodhpur',   'umaid-bhawan.com'),('hph-jodhpur',      'ajit-bhawan.com'),('hph-jodhpur',      'raas-jodhpur.com'),
  ('hph-mysore',    'lalitha-mahal.com'),('hph-mysore',       'radisson-mysore.com'),('hph-mysore',   'hotel-dasaprakash.com'),
  ('zbh-amsterdam', 'nhow-amsterdam.com'),('zbh-amsterdam',   'w-amsterdam.com'),('zbh-amsterdam',   'citizen-m.com'),
  ('zbh-frankfurt', 'marriott-frankfurt.com'),('zbh-frankfurt','hilton-frankfurt.com'),('zbh-frankfurt','steigenberger-frankfurt.com'),
  ('zbh-chicago',   'theriviera-chicago.com'),('zbh-chicago',  'peninsula-chicago.com'),('zbh-chicago', 'chicago-marriott.com'),
  ('zbh-singapore', 'raffles-sg.com'),('zbh-singapore',       'fullerton-sg.com'),('zbh-singapore',  'marina-bay-sands.com'),
  ('zbh-toronto',   'ritzcarlton-toronto.com'),('zbh-toronto', 'shangri-la-toronto.com'),('zbh-toronto','fairmont-royal-york.com'),
  ('hbh-edinburgh', 'the-witchery.com'),('hbh-edinburgh',     'hotel-missoni-edinburgh.com'),('hbh-edinburgh','balmoral-hotel.com'),
  ('hbh-lisbon',    'bairro-alto-hotel.com'),('hbh-lisbon',    'palacio-belmonte.com'),('hbh-lisbon',   'casa-do-principe.com'),
  ('hbh-prague',    'aria-hotel-prague.com'),('hbh-prague',    'four-seasons-prague.com'),('hbh-prague', 'hotel-josef.com'),
  ('hbh-barcelona', 'hotel-arts-barcelona.com'),('hbh-barcelona','w-barcelona.com'),('hbh-barcelona',  'grand-hotel-central.com'),
  ('hbh-amsterdam', 'pulitzer-amsterdam.com'),('hbh-amsterdam', 'seven-one-seven.com'),('hbh-amsterdam','andaz-amsterdam.com')
ON CONFLICT DO NOTHING;

-- ── Keywords ─────────────────────────────────────────────────────────────────
INSERT INTO keywords (id, property_id, keyword, search_volume, target_url) VALUES
  -- Meridian London
  ('mrd-lon-1','mrd-london','luxury hotel london hyde park',8100,'/rooms'),
  ('mrd-lon-2','mrd-london','meridian london hotel',2400,'/'),
  ('mrd-lon-3','mrd-london','best hotels hyde park',5400,'/about'),
  ('mrd-lon-4','mrd-london','london hotel deals',12100,'/offers'),
  ('mrd-lon-5','mrd-london','5 star hotels london',9900,'/'),
  ('mrd-lon-6','mrd-london','hotel near hyde park',3600,'/location'),
  ('mrd-lon-7','mrd-london','london luxury spa hotel',2900,'/spa'),
  ('mrd-lon-8','mrd-london','london hotel room booking',6600,'/book'),
  -- Meridian Paris
  ('mrd-par-1','mrd-paris','luxury hotel paris champs elysees',9900,'/rooms'),
  ('mrd-par-2','mrd-paris','meridian paris hotel',1900,'/'),
  ('mrd-par-3','mrd-paris','best paris luxury hotels',14800,'/'),
  ('mrd-par-4','mrd-paris','paris hotel eiffel tower view',6600,'/rooms/deluxe'),
  ('mrd-par-5','mrd-paris','5 star hotel paris',22200,'/'),
  ('mrd-par-6','mrd-paris','romantic hotel paris',8100,'/experiences'),
  ('mrd-par-7','mrd-paris','paris boutique hotel deal',4400,'/offers'),
  ('mrd-par-8','mrd-paris','hotel breakfast paris included',3200,'/dining'),
  -- Meridian Dubai
  ('mrd-dub-1','mrd-dubai','luxury hotel dubai marina',12100,'/rooms'),
  ('mrd-dub-2','mrd-dubai','meridian dubai hotel',3200,'/'),
  ('mrd-dub-3','mrd-dubai','dubai marina hotel deals',8100,'/offers'),
  ('mrd-dub-4','mrd-dubai','5 star hotel dubai marina',9900,'/'),
  ('mrd-dub-5','mrd-dubai','hotel pool dubai marina',5400,'/amenities'),
  ('mrd-dub-6','mrd-dubai','dubai hotel sea view room',6600,'/rooms/seaview'),
  ('mrd-dub-7','mrd-dubai','dubai new year hotel package',4400,'/packages'),
  ('mrd-dub-8','mrd-dubai','book hotel dubai online',18100,'/book'),
  -- Meridian New York
  ('mrd-ny-1','mrd-ny','luxury hotel new york midtown',18100,'/rooms'),
  ('mrd-ny-2','mrd-ny','meridian new york hotel',2900,'/'),
  ('mrd-ny-3','mrd-ny','midtown manhattan hotel',22200,'/'),
  ('mrd-ny-4','mrd-ny','times square hotel deals',27100,'/offers'),
  ('mrd-ny-5','mrd-ny','5 star hotel manhattan',14800,'/'),
  ('mrd-ny-6','mrd-ny','new york hotel with gym spa',8100,'/amenities'),
  ('mrd-ny-7','mrd-ny','nyc hotel near central park',9900,'/location'),
  ('mrd-ny-8','mrd-ny','cheap luxury hotels new york',33100,'/offers/lastminute'),
  -- Meridian Singapore
  ('mrd-sg-1','mrd-singapore','luxury hotel singapore orchard road',9900,'/rooms'),
  ('mrd-sg-2','mrd-singapore','meridian singapore hotel',1900,'/'),
  ('mrd-sg-3','mrd-singapore','best hotel orchard singapore',6600,'/'),
  ('mrd-sg-4','mrd-singapore','singapore 5 star hotel deal',12100,'/offers'),
  ('mrd-sg-5','mrd-singapore','hotel infinity pool singapore',8100,'/amenities'),
  ('mrd-sg-6','mrd-singapore','singapore family hotel orchard',5400,'/family'),
  ('mrd-sg-7','mrd-singapore','book hotel singapore best rate',14800,'/book'),
  ('mrd-sg-8','mrd-singapore','singapore luxury spa weekend',4400,'/spa'),
  -- Meridian Rome
  ('mrd-rom-1','mrd-rome','luxury hotel rome colosseum',6600,'/rooms'),
  ('mrd-rom-2','mrd-rome','meridian rome hotel',880,'/'),
  ('mrd-rom-3','mrd-rome','best hotel near colosseum rome',8100,'/location'),
  ('mrd-rom-4','mrd-rome','5 star rome hotel deal',9900,'/offers'),
  ('mrd-rom-5','mrd-rome','rome hotel breakfast included',5400,'/dining'),
  ('mrd-rom-6','mrd-rome','romantic hotel rome italy',7200,'/experiences'),
  ('mrd-rom-7','mrd-rome','rome hotel terrace view',3600,'/rooms/suite'),
  ('mrd-rom-8','mrd-rome','book rome hotel online cheap',14800,'/book'),
  -- Meridian Tokyo
  ('mrd-tok-1','mrd-tokyo','luxury hotel tokyo shinjuku',8100,'/rooms'),
  ('mrd-tok-2','mrd-tokyo','meridian tokyo hotel',2100,'/'),
  ('mrd-tok-3','mrd-tokyo','best hotel shinjuku tokyo',12100,'/'),
  ('mrd-tok-4','mrd-tokyo','tokyo hotel deals 2024',22200,'/offers'),
  ('mrd-tok-5','mrd-tokyo','5 star hotel tokyo',18100,'/'),
  ('mrd-tok-6','mrd-tokyo','tokyo hotel mount fuji view',4400,'/rooms/premium'),
  ('mrd-tok-7','mrd-tokyo','tokyo luxury business hotel',6600,'/business'),
  ('mrd-tok-8','mrd-tokyo','shinjuku hotel online booking',9900,'/book'),
  -- Meridian Sydney
  ('mrd-syd-1','mrd-sydney','luxury hotel sydney harbour',9900,'/rooms'),
  ('mrd-syd-2','mrd-sydney','meridian sydney hotel',1600,'/'),
  ('mrd-syd-3','mrd-sydney','sydney harbour view hotel',8100,'/rooms/harbour'),
  ('mrd-syd-4','mrd-sydney','best sydney hotel cbd',12100,'/'),
  ('mrd-syd-5','mrd-sydney','5 star hotel sydney deals',8100,'/offers'),
  ('mrd-syd-6','mrd-sydney','sydney hotel opera house',6600,'/location'),
  ('mrd-syd-7','mrd-sydney','sydney hotel weekend getaway',5400,'/packages'),
  ('mrd-syd-8','mrd-sydney','book sydney luxury hotel',14800,'/book'),
  -- Crestview Maldives
  ('crv-mal-1','crv-maldives','overwater bungalow maldives resort',22200,'/villas'),
  ('crv-mal-2','crv-maldives','crestview maldives resort',3200,'/'),
  ('crv-mal-3','crv-maldives','best maldives resort 2024',33100,'/'),
  ('crv-mal-4','crv-maldives','maldives honeymoon resort',18100,'/honeymoon'),
  ('crv-mal-5','crv-maldives','maldives all inclusive deal',27100,'/offers'),
  ('crv-mal-6','crv-maldives','water villa maldives price',14800,'/villas/water'),
  ('crv-mal-7','crv-maldives','maldives resort diving snorkeling',8100,'/activities'),
  ('crv-mal-8','crv-maldives','book maldives villa luxury',9900,'/book'),
  -- Crestview Bali
  ('crv-bal-1','crv-bali','luxury resort bali ubud',14800,'/rooms'),
  ('crv-bal-2','crv-bali','crestview bali resort',2100,'/'),
  ('crv-bal-3','crv-bali','best bali jungle resort',18100,'/'),
  ('crv-bal-4','crv-bali','bali yoga retreat resort',9900,'/wellness'),
  ('crv-bal-5','crv-bali','ubud rice terrace hotel',6600,'/location'),
  ('crv-bal-6','crv-bali','bali all inclusive resort',22200,'/offers'),
  ('crv-bal-7','crv-bali','bali spa hotel ubud',8100,'/spa'),
  ('crv-bal-8','crv-bali','book bali resort cheapest rate',12100,'/book'),
  -- Crestview Phuket
  ('crv-phu-1','crv-phuket','luxury beachfront resort phuket',18100,'/rooms'),
  ('crv-phu-2','crv-phuket','crestview phuket resort',2400,'/'),
  ('crv-phu-3','crv-phuket','phuket 5 star resort private beach',12100,'/beachfront'),
  ('crv-phu-4','crv-phuket','phuket resort deal package',22200,'/offers'),
  ('crv-phu-5','crv-phuket','patong beach hotel luxury',9900,'/location'),
  ('crv-phu-6','crv-phuket','phuket honeymoon resort',8100,'/honeymoon'),
  ('crv-phu-7','crv-phuket','thailand island resort snorkel dive',6600,'/activities'),
  ('crv-phu-8','crv-phuket','phuket hotel book direct best rate',14800,'/book'),
  -- Crestview Cancun
  ('crv-can-1','crv-cancun','all inclusive resort cancun',49500,'/all-inclusive'),
  ('crv-can-2','crv-cancun','crestview cancun resort',1900,'/'),
  ('crv-can-3','crv-cancun','luxury cancun resort oceanfront',14800,'/rooms'),
  ('crv-can-4','crv-cancun','cancun hotel zone deals',33100,'/offers'),
  ('crv-can-5','crv-cancun','adults only resort cancun',18100,'/adults-only'),
  ('crv-can-6','crv-cancun','cancun resort swim up bar',8100,'/amenities'),
  ('crv-can-7','crv-cancun','cancun spring break hotel',12100,'/packages/springbreak'),
  ('crv-can-8','crv-cancun','book cancun resort direct',22200,'/book'),
  -- Crestview Santorini
  ('crv-san-1','crv-santorini','luxury hotel santorini caldera view',12100,'/suites'),
  ('crv-san-2','crv-santorini','crestview santorini resort',1600,'/'),
  ('crv-san-3','crv-santorini','oia santorini hotel infinity pool',18100,'/amenities'),
  ('crv-san-4','crv-santorini','santorini honeymoon suite',14800,'/honeymoon'),
  ('crv-san-5','crv-santorini','best santorini hotel sunset view',22200,'/'),
  ('crv-san-6','crv-santorini','santorini cave hotel suite',9900,'/suites/cave'),
  ('crv-san-7','crv-santorini','santorini winery hotel tour',5400,'/experiences'),
  ('crv-san-8','crv-santorini','book santorini luxury suite direct',8100,'/book'),
  -- Crestview Abu Dhabi
  ('crv-ad-1','crv-abudhabi','luxury hotel abu dhabi corniche',8100,'/rooms'),
  ('crv-ad-2','crv-abudhabi','crestview abu dhabi hotel',1100,'/'),
  ('crv-ad-3','crv-abudhabi','abu dhabi 5 star hotel beach',9900,'/beachfront'),
  ('crv-ad-4','crv-abudhabi','abu dhabi hotel weekend deal',6600,'/offers'),
  ('crv-ad-5','crv-abudhabi','family hotel abu dhabi',12100,'/family'),
  ('crv-ad-6','crv-abudhabi','abu dhabi hotel yas island',8100,'/packages'),
  ('crv-ad-7','crv-abudhabi','abu dhabi business hotel conference',5400,'/meetings'),
  ('crv-ad-8','crv-abudhabi','book abu dhabi luxury resort',9900,'/book'),
  -- Heritage Jaipur
  ('hph-jai-1','hph-jaipur','heritage palace hotel jaipur',8100,'/rooms'),
  ('hph-jai-2','hph-jaipur','heritage jaipur palace',2400,'/'),
  ('hph-jai-3','hph-jaipur','luxury hotel jaipur pink city',12100,'/'),
  ('hph-jai-4','hph-jaipur','rajasthan palace hotel deal',9900,'/offers'),
  ('hph-jai-5','hph-jaipur','jaipur fort palace stay',6600,'/experiences'),
  ('hph-jai-6','hph-jaipur','india palace hotel luxury',8100,'/'),
  ('hph-jai-7','hph-jaipur','jaipur wedding venue palace',5400,'/weddings'),
  ('hph-jai-8','hph-jaipur','book jaipur palace hotel online',14800,'/book'),
  -- Heritage Udaipur
  ('hph-uda-1','hph-udaipur','palace hotel udaipur lake',9900,'/rooms'),
  ('hph-uda-2','hph-udaipur','heritage udaipur palace hotel',1900,'/'),
  ('hph-uda-3','hph-udaipur','udaipur lake view hotel',12100,'/rooms/lakeview'),
  ('hph-uda-4','hph-udaipur','luxury rajasthan heritage hotel',8100,'/'),
  ('hph-uda-5','hph-udaipur','udaipur honeymoon hotel',7200,'/honeymoon'),
  ('hph-uda-6','hph-udaipur','india royal palace stay experience',6600,'/experiences'),
  ('hph-uda-7','hph-udaipur','udaipur hotel boat ride lake pichola',4400,'/activities'),
  ('hph-uda-8','hph-udaipur','book heritage udaipur hotel',9900,'/book'),
  -- Heritage Agra
  ('hph-agr-1','hph-agra','hotel agra taj mahal view',14800,'/rooms/tajview'),
  ('hph-agr-2','hph-agra','heritage agra palace hotel',1600,'/'),
  ('hph-agr-3','hph-agra','luxury hotel near taj mahal agra',18100,'/location'),
  ('hph-agr-4','hph-agra','agra hotel sunrise taj mahal',9900,'/rooms/suite'),
  ('hph-agr-5','hph-agra','india heritage tour hotel agra',8100,'/packages'),
  ('hph-agr-6','hph-agra','agra hotel deal golden triangle',6600,'/offers'),
  ('hph-agr-7','hph-agra','5 star hotel agra india',12100,'/'),
  ('hph-agr-8','hph-agra','book agra luxury hotel direct',9900,'/book'),
  -- Heritage Jodhpur
  ('hph-jod-1','hph-jodhpur','palace hotel jodhpur blue city',7200,'/rooms'),
  ('hph-jod-2','hph-jodhpur','heritage jodhpur palace hotel',1100,'/'),
  ('hph-jod-3','hph-jodhpur','jodhpur fort view hotel',5400,'/rooms/fortview'),
  ('hph-jod-4','hph-jodhpur','luxury rajasthan fort hotel',8100,'/'),
  ('hph-jod-5','hph-jodhpur','jodhpur blue city tour hotel',6600,'/experiences'),
  ('hph-jod-6','hph-jodhpur','india desert safari heritage hotel',4400,'/activities'),
  ('hph-jod-7','hph-jodhpur','jodhpur rooftop restaurant hotel',3600,'/dining'),
  ('hph-jod-8','hph-jodhpur','book jodhpur heritage hotel',8100,'/book'),
  -- Heritage Mysore
  ('hph-mys-1','hph-mysore','heritage palace hotel mysore',4400,'/rooms'),
  ('hph-mys-2','hph-mysore','heritage mysore palace stay',880,'/'),
  ('hph-mys-3','hph-mysore','luxury hotel mysore karnataka',6600,'/'),
  ('hph-mys-4','hph-mysore','mysore dasara festival hotel',5400,'/packages/dasara'),
  ('hph-mys-5','hph-mysore','mysore palace view hotel',8100,'/rooms/palaceview'),
  ('hph-mys-6','hph-mysore','karnataka heritage tour hotel',4400,'/experiences'),
  ('hph-mys-7','hph-mysore','mysore zoo garden hotel near',3600,'/location'),
  ('hph-mys-8','hph-mysore','book heritage mysore hotel',6600,'/book'),
  -- Zenith Amsterdam
  ('zbh-ams-1','zbh-amsterdam','business hotel amsterdam airport',12100,'/rooms/business'),
  ('zbh-ams-2','zbh-amsterdam','zenith amsterdam hotel',1900,'/'),
  ('zbh-ams-3','zbh-amsterdam','schiphol hotel with conference room',8100,'/meetings'),
  ('zbh-ams-4','zbh-amsterdam','amsterdam hotel near airport cheap',18100,'/offers'),
  ('zbh-ams-5','zbh-amsterdam','amsterdam executive hotel',6600,'/executive'),
  ('zbh-ams-6','zbh-amsterdam','amsterdam hotel city center canal',22200,'/location'),
  ('zbh-ams-7','zbh-amsterdam','netherlands business travel hotel',9900,'/business'),
  ('zbh-ams-8','zbh-amsterdam','amsterdam hotel book online',27100,'/book'),
  -- Zenith Frankfurt
  ('zbh-fra-1','zbh-frankfurt','business hotel frankfurt messe',9900,'/rooms/business'),
  ('zbh-fra-2','zbh-frankfurt','zenith frankfurt hotel',1600,'/'),
  ('zbh-fra-3','zbh-frankfurt','frankfurt trade fair hotel',12100,'/meetings/tradeshows'),
  ('zbh-fra-4','zbh-frankfurt','hotel near frankfurt airport',18100,'/location'),
  ('zbh-fra-5','zbh-frankfurt','frankfurt executive lounge hotel',5400,'/executive'),
  ('zbh-fra-6','zbh-frankfurt','frankfurt hotel conference facilities',7200,'/meetings'),
  ('zbh-fra-7','zbh-frankfurt','germany business travel hotel deal',14800,'/offers'),
  ('zbh-fra-8','zbh-frankfurt','book frankfurt hotel direct rate',12100,'/book'),
  -- Zenith Chicago
  ('zbh-chi-1','zbh-chicago','business hotel chicago loop downtown',12100,'/rooms/business'),
  ('zbh-chi-2','zbh-chicago','zenith chicago hotel',1900,'/'),
  ('zbh-chi-3','zbh-chicago','chicago corporate hotel conference',9900,'/meetings'),
  ('zbh-chi-4','zbh-chicago','chicago hotel near o''hare airport',14800,'/location'),
  ('zbh-chi-5','zbh-chicago','chicago hotel deal last minute',22200,'/offers'),
  ('zbh-chi-6','zbh-chicago','chicago loop hotel walk to lakefront',8100,'/location'),
  ('zbh-chi-7','zbh-chicago','chicago executive hotel fitness center',6600,'/amenities'),
  ('zbh-chi-8','zbh-chicago','book chicago hotel best rate direct',18100,'/book'),
  -- Zenith Singapore
  ('zbh-sg-1','zbh-singapore','business hotel singapore marina bay',12100,'/rooms/business'),
  ('zbh-sg-2','zbh-singapore','zenith singapore hotel',2100,'/'),
  ('zbh-sg-3','zbh-singapore','singapore corporate meeting hotel',9900,'/meetings'),
  ('zbh-sg-4','zbh-singapore','singapore hotel conference facilities',8100,'/meetings/events'),
  ('zbh-sg-5','zbh-singapore','cbd hotel singapore business district',14800,'/location'),
  ('zbh-sg-6','zbh-singapore','singapore hotel deal direct booking',22200,'/offers'),
  ('zbh-sg-7','zbh-singapore','singapore executive lounge hotel',6600,'/executive'),
  ('zbh-sg-8','zbh-singapore','book singapore hotel marina bay view',18100,'/book'),
  -- Zenith Toronto
  ('zbh-tor-1','zbh-toronto','business hotel toronto bay street',8100,'/rooms/business'),
  ('zbh-tor-2','zbh-toronto','zenith toronto hotel',1300,'/'),
  ('zbh-tor-3','zbh-toronto','toronto downtown hotel corporate rate',12100,'/corporate'),
  ('zbh-tor-4','zbh-toronto','toronto hotel near financial district',9900,'/location'),
  ('zbh-tor-5','zbh-toronto','toronto conference hotel meetings',7200,'/meetings'),
  ('zbh-tor-6','zbh-toronto','toronto hotel deal weekend',14800,'/offers'),
  ('zbh-tor-7','zbh-toronto','toronto hotel cn tower view',6600,'/rooms/cityview'),
  ('zbh-tor-8','zbh-toronto','book toronto hotel best rate',18100,'/book'),
  -- Harbour Edinburgh
  ('hbh-edi-1','hbh-edinburgh','boutique hotel edinburgh old town',8100,'/rooms'),
  ('hbh-edi-2','hbh-edinburgh','harbour edinburgh hotel',1100,'/'),
  ('hbh-edi-3','hbh-edinburgh','edinburgh castle view hotel',12100,'/rooms/castleview'),
  ('hbh-edi-4','hbh-edinburgh','scotland boutique hotel deal',9900,'/offers'),
  ('hbh-edi-5','hbh-edinburgh','edinburgh fringe festival hotel',7200,'/packages/fringe'),
  ('hbh-edi-6','hbh-edinburgh','royal mile hotel edinburgh',14800,'/location'),
  ('hbh-edi-7','hbh-edinburgh','edinburgh hotel whisky bar',5400,'/dining'),
  ('hbh-edi-8','hbh-edinburgh','book edinburgh boutique hotel',9900,'/book'),
  -- Harbour Lisbon
  ('hbh-lis-1','hbh-lisbon','boutique hotel lisbon alfama',6600,'/rooms'),
  ('hbh-lis-2','hbh-lisbon','harbour lisbon hotel',880,'/'),
  ('hbh-lis-3','hbh-lisbon','lisbon historic district hotel',8100,'/location'),
  ('hbh-lis-4','hbh-lisbon','lisbon fado music hotel',5400,'/experiences'),
  ('hbh-lis-5','hbh-lisbon','portugal boutique hotel deal',9900,'/offers'),
  ('hbh-lis-6','hbh-lisbon','lisbon hotel tram tour',7200,'/activities'),
  ('hbh-lis-7','hbh-lisbon','lisbon ocean view boutique hotel',4400,'/rooms/seaview'),
  ('hbh-lis-8','hbh-lisbon','book lisbon boutique hotel cheap',12100,'/book'),
  -- Harbour Prague
  ('hbh-pra-1','hbh-prague','boutique hotel prague old town',9900,'/rooms'),
  ('hbh-pra-2','hbh-prague','harbour prague boutique hotel',1100,'/'),
  ('hbh-pra-3','hbh-prague','prague castle view hotel',7200,'/rooms/castleview'),
  ('hbh-pra-4','hbh-prague','czech republic boutique hotel deal',6600,'/offers'),
  ('hbh-pra-5','hbh-prague','prague hotel charles bridge walk',8100,'/location'),
  ('hbh-pra-6','hbh-prague','prague hotel jazz bar live music',4400,'/dining'),
  ('hbh-pra-7','hbh-prague','europe boutique hotel weekend break',12100,'/packages'),
  ('hbh-pra-8','hbh-prague','book prague boutique hotel online',14800,'/book'),
  -- Harbour Barcelona
  ('hbh-bar-1','hbh-barcelona','boutique hotel barcelona gothic quarter',12100,'/rooms'),
  ('hbh-bar-2','hbh-barcelona','harbour barcelona hotel',1600,'/'),
  ('hbh-bar-3','hbh-barcelona','barcelona hotel near sagrada familia',14800,'/location'),
  ('hbh-bar-4','hbh-barcelona','spain boutique hotel deal',9900,'/offers'),
  ('hbh-bar-5','hbh-barcelona','barcelona hotel rooftop pool',8100,'/amenities'),
  ('hbh-bar-6','hbh-barcelona','barcelona hotel las ramblas walkable',18100,'/location'),
  ('hbh-bar-7','hbh-barcelona','barcelona food tour hotel package',6600,'/experiences'),
  ('hbh-bar-8','hbh-barcelona','book barcelona boutique hotel direct',12100,'/book'),
  -- Harbour Amsterdam
  ('hbh-ada-1','hbh-amsterdam','boutique hotel amsterdam canal house',8100,'/rooms'),
  ('hbh-ada-2','hbh-amsterdam','harbour amsterdam canal hotel',1100,'/'),
  ('hbh-ada-3','hbh-amsterdam','amsterdam historic canal hotel',9900,'/location'),
  ('hbh-ada-4','hbh-amsterdam','netherlands boutique hotel deal',7200,'/offers'),
  ('hbh-ada-5','hbh-amsterdam','amsterdam hotel bike rental included',6600,'/amenities'),
  ('hbh-ada-6','hbh-amsterdam','amsterdam museum hotel deal',12100,'/packages/museum'),
  ('hbh-ada-7','hbh-amsterdam','amsterdam hotel jordaan neighbourhood',9900,'/location'),
  ('hbh-ada-8','hbh-amsterdam','book amsterdam boutique hotel',14800,'/book')
ON CONFLICT DO NOTHING;

-- ── Keyword Rankings (current vs previous) ───────────────────────────────────
INSERT INTO keyword_rankings (keyword_id, recorded_at, current_rank, previous_rank) VALUES
  ('mrd-lon-1',CURRENT_DATE,14,18),('mrd-lon-2',CURRENT_DATE,1,1),('mrd-lon-3',CURRENT_DATE,22,15),
  ('mrd-lon-4',CURRENT_DATE,38,29),('mrd-lon-5',CURRENT_DATE,11,8),('mrd-lon-6',CURRENT_DATE,7,6),
  ('mrd-lon-7',CURRENT_DATE,19,25),('mrd-lon-8',CURRENT_DATE,45,33),
  ('mrd-par-1',CURRENT_DATE,8,12),('mrd-par-2',CURRENT_DATE,1,1),('mrd-par-3',CURRENT_DATE,15,18),
  ('mrd-par-4',CURRENT_DATE,12,16),('mrd-par-5',CURRENT_DATE,21,25),('mrd-par-6',CURRENT_DATE,9,7),
  ('mrd-par-7',CURRENT_DATE,28,22),('mrd-par-8',CURRENT_DATE,17,21),
  ('mrd-dub-1',CURRENT_DATE,5,9),('mrd-dub-2',CURRENT_DATE,1,1),('mrd-dub-3',CURRENT_DATE,7,12),
  ('mrd-dub-4',CURRENT_DATE,4,7),('mrd-dub-5',CURRENT_DATE,9,14),('mrd-dub-6',CURRENT_DATE,6,8),
  ('mrd-dub-7',CURRENT_DATE,14,18),('mrd-dub-8',CURRENT_DATE,19,24),
  ('mrd-ny-1',CURRENT_DATE,9,11),('mrd-ny-2',CURRENT_DATE,1,1),('mrd-ny-3',CURRENT_DATE,18,24),
  ('mrd-ny-4',CURRENT_DATE,24,31),('mrd-ny-5',CURRENT_DATE,12,15),('mrd-ny-6',CURRENT_DATE,8,10),
  ('mrd-ny-7',CURRENT_DATE,16,20),('mrd-ny-8',CURRENT_DATE,31,28),
  ('mrd-sg-1',CURRENT_DATE,11,13),('mrd-sg-2',CURRENT_DATE,1,1),('mrd-sg-3',CURRENT_DATE,8,11),
  ('mrd-sg-4',CURRENT_DATE,17,22),('mrd-sg-5',CURRENT_DATE,14,16),('mrd-sg-6',CURRENT_DATE,9,8),
  ('mrd-sg-7',CURRENT_DATE,22,27),('mrd-sg-8',CURRENT_DATE,19,23),
  ('mrd-rom-1',CURRENT_DATE,28,19),('mrd-rom-2',CURRENT_DATE,1,1),('mrd-rom-3',CURRENT_DATE,34,24),
  ('mrd-rom-4',CURRENT_DATE,41,29),('mrd-rom-5',CURRENT_DATE,37,26),('mrd-rom-6',CURRENT_DATE,22,14),
  ('mrd-rom-7',CURRENT_DATE,31,21),('mrd-rom-8',CURRENT_DATE,49,37),
  ('mrd-tok-1',CURRENT_DATE,6,9),('mrd-tok-2',CURRENT_DATE,1,1),('mrd-tok-3',CURRENT_DATE,4,7),
  ('mrd-tok-4',CURRENT_DATE,14,19),('mrd-tok-5',CURRENT_DATE,11,15),('mrd-tok-6',CURRENT_DATE,8,13),
  ('mrd-tok-7',CURRENT_DATE,9,12),('mrd-tok-8',CURRENT_DATE,16,21),
  ('mrd-syd-1',CURRENT_DATE,10,12),('mrd-syd-2',CURRENT_DATE,1,1),('mrd-syd-3',CURRENT_DATE,7,9),
  ('mrd-syd-4',CURRENT_DATE,13,16),('mrd-syd-5',CURRENT_DATE,21,25),('mrd-syd-6',CURRENT_DATE,9,11),
  ('mrd-syd-7',CURRENT_DATE,17,22),('mrd-syd-8',CURRENT_DATE,24,29),
  ('crv-mal-1',CURRENT_DATE,4,7),('crv-mal-2',CURRENT_DATE,1,1),('crv-mal-3',CURRENT_DATE,8,12),
  ('crv-mal-4',CURRENT_DATE,6,9),('crv-mal-5',CURRENT_DATE,11,16),('crv-mal-6',CURRENT_DATE,9,14),
  ('crv-mal-7',CURRENT_DATE,5,8),('crv-mal-8',CURRENT_DATE,14,19),
  ('crv-bal-1',CURRENT_DATE,19,12),('crv-bal-2',CURRENT_DATE,1,1),('crv-bal-3',CURRENT_DATE,26,18),
  ('crv-bal-4',CURRENT_DATE,22,15),('crv-bal-5',CURRENT_DATE,31,22),('crv-bal-6',CURRENT_DATE,37,25),
  ('crv-bal-7',CURRENT_DATE,24,17),('crv-bal-8',CURRENT_DATE,42,31),
  ('crv-phu-1',CURRENT_DATE,7,10),('crv-phu-2',CURRENT_DATE,1,1),('crv-phu-3',CURRENT_DATE,9,13),
  ('crv-phu-4',CURRENT_DATE,16,21),('crv-phu-5',CURRENT_DATE,12,15),('crv-phu-6',CURRENT_DATE,8,11),
  ('crv-phu-7',CURRENT_DATE,14,18),('crv-phu-8',CURRENT_DATE,21,26),
  ('crv-can-1',CURRENT_DATE,22,16),('crv-can-2',CURRENT_DATE,1,1),('crv-can-3',CURRENT_DATE,29,21),
  ('crv-can-4',CURRENT_DATE,41,31),('crv-can-5',CURRENT_DATE,18,12),('crv-can-6',CURRENT_DATE,26,19),
  ('crv-can-7',CURRENT_DATE,34,26),('crv-can-8',CURRENT_DATE,47,36),
  ('crv-san-1',CURRENT_DATE,6,9),('crv-san-2',CURRENT_DATE,1,1),('crv-san-3',CURRENT_DATE,8,12),
  ('crv-san-4',CURRENT_DATE,7,11),('crv-san-5',CURRENT_DATE,11,15),('crv-san-6',CURRENT_DATE,9,13),
  ('crv-san-7',CURRENT_DATE,14,18),('crv-san-8',CURRENT_DATE,19,23),
  ('crv-ad-1',CURRENT_DATE,12,15),('crv-ad-2',CURRENT_DATE,1,1),('crv-ad-3',CURRENT_DATE,16,20),
  ('crv-ad-4',CURRENT_DATE,24,29),('crv-ad-5',CURRENT_DATE,19,23),('crv-ad-6',CURRENT_DATE,28,33),
  ('crv-ad-7',CURRENT_DATE,14,18),('crv-ad-8',CURRENT_DATE,31,36),
  ('hph-jai-1',CURRENT_DATE,33,21),('hph-jai-2',CURRENT_DATE,1,1),('hph-jai-3',CURRENT_DATE,41,28),
  ('hph-jai-4',CURRENT_DATE,47,33),('hph-jai-5',CURRENT_DATE,38,26),('hph-jai-6',CURRENT_DATE,29,19),
  ('hph-jai-7',CURRENT_DATE,22,15),('hph-jai-8',CURRENT_DATE,51,39),
  ('hph-uda-1',CURRENT_DATE,17,12),('hph-uda-2',CURRENT_DATE,1,1),('hph-uda-3',CURRENT_DATE,22,16),
  ('hph-uda-4',CURRENT_DATE,29,21),('hph-uda-5',CURRENT_DATE,14,10),('hph-uda-6',CURRENT_DATE,26,19),
  ('hph-uda-7',CURRENT_DATE,18,13),('hph-uda-8',CURRENT_DATE,37,28),
  ('hph-agr-1',CURRENT_DATE,9,13),('hph-agr-2',CURRENT_DATE,1,1),('hph-agr-3',CURRENT_DATE,12,17),
  ('hph-agr-4',CURRENT_DATE,8,12),('hph-agr-5',CURRENT_DATE,14,19),('hph-agr-6',CURRENT_DATE,18,23),
  ('hph-agr-7',CURRENT_DATE,21,26),('hph-agr-8',CURRENT_DATE,28,33),
  ('hph-jod-1',CURRENT_DATE,11,14),('hph-jod-2',CURRENT_DATE,1,1),('hph-jod-3',CURRENT_DATE,9,12),
  ('hph-jod-4',CURRENT_DATE,16,20),('hph-jod-5',CURRENT_DATE,13,17),('hph-jod-6',CURRENT_DATE,19,24),
  ('hph-jod-7',CURRENT_DATE,8,10),('hph-jod-8',CURRENT_DATE,24,29),
  ('hph-mys-1',CURRENT_DATE,8,10),('hph-mys-2',CURRENT_DATE,1,1),('hph-mys-3',CURRENT_DATE,13,16),
  ('hph-mys-4',CURRENT_DATE,9,12),('hph-mys-5',CURRENT_DATE,11,14),('hph-mys-6',CURRENT_DATE,16,19),
  ('hph-mys-7',CURRENT_DATE,12,15),('hph-mys-8',CURRENT_DATE,21,25),
  ('zbh-ams-1',CURRENT_DATE,6,9),('zbh-ams-2',CURRENT_DATE,1,1),('zbh-ams-3',CURRENT_DATE,4,7),
  ('zbh-ams-4',CURRENT_DATE,11,15),('zbh-ams-5',CURRENT_DATE,8,12),('zbh-ams-6',CURRENT_DATE,18,23),
  ('zbh-ams-7',CURRENT_DATE,14,18),('zbh-ams-8',CURRENT_DATE,21,26),
  ('zbh-fra-1',CURRENT_DATE,5,8),('zbh-fra-2',CURRENT_DATE,1,1),('zbh-fra-3',CURRENT_DATE,7,11),
  ('zbh-fra-4',CURRENT_DATE,13,17),('zbh-fra-5',CURRENT_DATE,9,13),('zbh-fra-6',CURRENT_DATE,6,9),
  ('zbh-fra-7',CURRENT_DATE,17,22),('zbh-fra-8',CURRENT_DATE,22,27),
  ('zbh-chi-1',CURRENT_DATE,9,11),('zbh-chi-2',CURRENT_DATE,1,1),('zbh-chi-3',CURRENT_DATE,7,9),
  ('zbh-chi-4',CURRENT_DATE,16,18),('zbh-chi-5',CURRENT_DATE,28,24),('zbh-chi-6',CURRENT_DATE,12,14),
  ('zbh-chi-7',CURRENT_DATE,14,17),('zbh-chi-8',CURRENT_DATE,29,25),
  ('zbh-sg-1',CURRENT_DATE,5,8),('zbh-sg-2',CURRENT_DATE,1,1),('zbh-sg-3',CURRENT_DATE,4,7),
  ('zbh-sg-4',CURRENT_DATE,6,10),('zbh-sg-5',CURRENT_DATE,9,13),('zbh-sg-6',CURRENT_DATE,14,19),
  ('zbh-sg-7',CURRENT_DATE,11,15),('zbh-sg-8',CURRENT_DATE,18,23),
  ('zbh-tor-1',CURRENT_DATE,10,13),('zbh-tor-2',CURRENT_DATE,1,1),('zbh-tor-3',CURRENT_DATE,14,18),
  ('zbh-tor-4',CURRENT_DATE,12,16),('zbh-tor-5',CURRENT_DATE,8,12),('zbh-tor-6',CURRENT_DATE,22,26),
  ('zbh-tor-7',CURRENT_DATE,19,24),('zbh-tor-8',CURRENT_DATE,27,32),
  ('hbh-edi-1',CURRENT_DATE,5,8),('hbh-edi-2',CURRENT_DATE,1,1),('hbh-edi-3',CURRENT_DATE,7,10),
  ('hbh-edi-4',CURRENT_DATE,9,13),('hbh-edi-5',CURRENT_DATE,11,15),('hbh-edi-6',CURRENT_DATE,14,18),
  ('hbh-edi-7',CURRENT_DATE,8,12),('hbh-edi-8',CURRENT_DATE,16,21),
  ('hbh-lis-1',CURRENT_DATE,24,16),('hbh-lis-2',CURRENT_DATE,1,1),('hbh-lis-3',CURRENT_DATE,31,22),
  ('hbh-lis-4',CURRENT_DATE,27,19),('hbh-lis-5',CURRENT_DATE,38,27),('hbh-lis-6',CURRENT_DATE,22,15),
  ('hbh-lis-7',CURRENT_DATE,34,24),('hbh-lis-8',CURRENT_DATE,45,33),
  ('hbh-pra-1',CURRENT_DATE,8,11),('hbh-pra-2',CURRENT_DATE,1,1),('hbh-pra-3',CURRENT_DATE,11,14),
  ('hbh-pra-4',CURRENT_DATE,14,18),('hbh-pra-5',CURRENT_DATE,12,16),('hbh-pra-6',CURRENT_DATE,9,13),
  ('hbh-pra-7',CURRENT_DATE,19,24),('hbh-pra-8',CURRENT_DATE,23,28),
  ('hbh-bar-1',CURRENT_DATE,7,10),('hbh-bar-2',CURRENT_DATE,1,1),('hbh-bar-3',CURRENT_DATE,9,13),
  ('hbh-bar-4',CURRENT_DATE,12,16),('hbh-bar-5',CURRENT_DATE,8,12),('hbh-bar-6',CURRENT_DATE,16,21),
  ('hbh-bar-7',CURRENT_DATE,11,15),('hbh-bar-8',CURRENT_DATE,19,24),
  ('hbh-ada-1',CURRENT_DATE,13,10),('hbh-ada-2',CURRENT_DATE,1,1),('hbh-ada-3',CURRENT_DATE,16,13),
  ('hbh-ada-4',CURRENT_DATE,21,17),('hbh-ada-5',CURRENT_DATE,9,7),('hbh-ada-6',CURRENT_DATE,18,15),
  ('hbh-ada-7',CURRENT_DATE,14,11),('hbh-ada-8',CURRENT_DATE,26,22)
ON CONFLICT DO NOTHING;

-- ── Competitor Rankings ──────────────────────────────────────────────────────
INSERT INTO competitor_rankings (keyword_id, domain, recorded_at, rank) VALUES
  ('mrd-lon-1','marriott-london.com',CURRENT_DATE,3),('mrd-lon-1','hilton-london.co.uk',CURRENT_DATE,7),('mrd-lon-1','radisson-hyde.com',CURRENT_DATE,11),
  ('mrd-lon-2','marriott-london.com',CURRENT_DATE,NULL),('mrd-lon-2','hilton-london.co.uk',CURRENT_DATE,NULL),('mrd-lon-2','radisson-hyde.com',CURRENT_DATE,NULL),
  ('mrd-lon-3','marriott-london.com',CURRENT_DATE,4),('mrd-lon-3','hilton-london.co.uk',CURRENT_DATE,9),('mrd-lon-3','radisson-hyde.com',CURRENT_DATE,14),
  ('mrd-lon-4','marriott-london.com',CURRENT_DATE,8),('mrd-lon-4','hilton-london.co.uk',CURRENT_DATE,12),('mrd-lon-4','radisson-hyde.com',CURRENT_DATE,21),
  ('mrd-lon-5','marriott-london.com',CURRENT_DATE,2),('mrd-lon-5','hilton-london.co.uk',CURRENT_DATE,5),('mrd-lon-5','radisson-hyde.com',CURRENT_DATE,16),
  ('mrd-lon-6','marriott-london.com',CURRENT_DATE,3),('mrd-lon-6','hilton-london.co.uk',CURRENT_DATE,10),('mrd-lon-6','radisson-hyde.com',CURRENT_DATE,13),
  ('mrd-lon-7','marriott-london.com',CURRENT_DATE,6),('mrd-lon-7','hilton-london.co.uk',CURRENT_DATE,NULL),('mrd-lon-7','radisson-hyde.com',CURRENT_DATE,28),
  ('mrd-lon-8','marriott-london.com',CURRENT_DATE,9),('mrd-lon-8','hilton-london.co.uk',CURRENT_DATE,15),('mrd-lon-8','radisson-hyde.com',CURRENT_DATE,NULL),
  ('mrd-par-1','fourseasons-paris.com',CURRENT_DATE,2),('mrd-par-1','ritz-paris.com',CURRENT_DATE,4),('mrd-par-1','plaza-athenee.com',CURRENT_DATE,6),
  ('mrd-par-2','fourseasons-paris.com',CURRENT_DATE,NULL),('mrd-par-2','ritz-paris.com',CURRENT_DATE,NULL),('mrd-par-2','plaza-athenee.com',CURRENT_DATE,NULL),
  ('mrd-par-3','fourseasons-paris.com',CURRENT_DATE,1),('mrd-par-3','ritz-paris.com',CURRENT_DATE,3),('mrd-par-3','plaza-athenee.com',CURRENT_DATE,7),
  ('mrd-par-4','fourseasons-paris.com',CURRENT_DATE,5),('mrd-par-4','ritz-paris.com',CURRENT_DATE,8),('mrd-par-4','plaza-athenee.com',CURRENT_DATE,11),
  ('mrd-par-5','fourseasons-paris.com',CURRENT_DATE,2),('mrd-par-5','ritz-paris.com',CURRENT_DATE,4),('mrd-par-5','plaza-athenee.com',CURRENT_DATE,9),
  ('mrd-par-6','fourseasons-paris.com',CURRENT_DATE,3),('mrd-par-6','ritz-paris.com',CURRENT_DATE,6),('mrd-par-6','plaza-athenee.com',CURRENT_DATE,14),
  ('mrd-par-7','fourseasons-paris.com',CURRENT_DATE,7),('mrd-par-7','ritz-paris.com',CURRENT_DATE,NULL),('mrd-par-7','plaza-athenee.com',CURRENT_DATE,17),
  ('mrd-par-8','fourseasons-paris.com',CURRENT_DATE,4),('mrd-par-8','ritz-paris.com',CURRENT_DATE,9),('mrd-par-8','plaza-athenee.com',CURRENT_DATE,12),
  ('mrd-dub-1','address-dubai.com',CURRENT_DATE,2),('mrd-dub-1','atlantis-dubai.com',CURRENT_DATE,8),('mrd-dub-1','burj-hotel.com',CURRENT_DATE,11),
  ('mrd-dub-2','address-dubai.com',CURRENT_DATE,NULL),('mrd-dub-2','atlantis-dubai.com',CURRENT_DATE,NULL),('mrd-dub-2','burj-hotel.com',CURRENT_DATE,NULL),
  ('mrd-dub-3','address-dubai.com',CURRENT_DATE,3),('mrd-dub-3','atlantis-dubai.com',CURRENT_DATE,6),('mrd-dub-3','burj-hotel.com',CURRENT_DATE,9),
  ('mrd-dub-4','address-dubai.com',CURRENT_DATE,1),('mrd-dub-4','atlantis-dubai.com',CURRENT_DATE,10),('mrd-dub-4','burj-hotel.com',CURRENT_DATE,15),
  ('mrd-dub-5','address-dubai.com',CURRENT_DATE,4),('mrd-dub-5','atlantis-dubai.com',CURRENT_DATE,7),('mrd-dub-5','burj-hotel.com',CURRENT_DATE,12),
  ('mrd-dub-6','address-dubai.com',CURRENT_DATE,2),('mrd-dub-6','atlantis-dubai.com',CURRENT_DATE,11),('mrd-dub-6','burj-hotel.com',CURRENT_DATE,14),
  ('mrd-dub-7','address-dubai.com',CURRENT_DATE,5),('mrd-dub-7','atlantis-dubai.com',CURRENT_DATE,9),('mrd-dub-7','burj-hotel.com',CURRENT_DATE,17),
  ('mrd-dub-8','address-dubai.com',CURRENT_DATE,7),('mrd-dub-8','atlantis-dubai.com',CURRENT_DATE,13),('mrd-dub-8','burj-hotel.com',CURRENT_DATE,22),
  ('mrd-ny-1','plaza-nyc.com',CURRENT_DATE,2),('mrd-ny-1','waldorf-astoria.com',CURRENT_DATE,5),('mrd-ny-1','the-mark-hotel.com',CURRENT_DATE,14),
  ('mrd-ny-2','plaza-nyc.com',CURRENT_DATE,NULL),('mrd-ny-2','waldorf-astoria.com',CURRENT_DATE,NULL),('mrd-ny-2','the-mark-hotel.com',CURRENT_DATE,NULL),
  ('mrd-ny-3','plaza-nyc.com',CURRENT_DATE,3),('mrd-ny-3','waldorf-astoria.com',CURRENT_DATE,8),('mrd-ny-3','the-mark-hotel.com',CURRENT_DATE,16),
  ('mrd-ny-4','plaza-nyc.com',CURRENT_DATE,6),('mrd-ny-4','waldorf-astoria.com',CURRENT_DATE,12),('mrd-ny-4','the-mark-hotel.com',CURRENT_DATE,19),
  ('mrd-ny-5','plaza-nyc.com',CURRENT_DATE,1),('mrd-ny-5','waldorf-astoria.com',CURRENT_DATE,4),('mrd-ny-5','the-mark-hotel.com',CURRENT_DATE,11),
  ('mrd-ny-6','plaza-nyc.com',CURRENT_DATE,3),('mrd-ny-6','waldorf-astoria.com',CURRENT_DATE,6),('mrd-ny-6','the-mark-hotel.com',CURRENT_DATE,17),
  ('mrd-ny-7','plaza-nyc.com',CURRENT_DATE,2),('mrd-ny-7','waldorf-astoria.com',CURRENT_DATE,9),('mrd-ny-7','the-mark-hotel.com',CURRENT_DATE,13),
  ('mrd-ny-8','plaza-nyc.com',CURRENT_DATE,8),('mrd-ny-8','waldorf-astoria.com',CURRENT_DATE,14),('mrd-ny-8','the-mark-hotel.com',CURRENT_DATE,22),
  ('crv-mal-1','soneva-maldives.com',CURRENT_DATE,1),('crv-mal-1','gili-lankanfushi.com',CURRENT_DATE,3),('crv-mal-1','anantara-maldives.com',CURRENT_DATE,6),
  ('crv-mal-2','soneva-maldives.com',CURRENT_DATE,NULL),('crv-mal-2','gili-lankanfushi.com',CURRENT_DATE,NULL),('crv-mal-2','anantara-maldives.com',CURRENT_DATE,NULL),
  ('crv-mal-3','soneva-maldives.com',CURRENT_DATE,2),('crv-mal-3','gili-lankanfushi.com',CURRENT_DATE,5),('crv-mal-3','anantara-maldives.com',CURRENT_DATE,9),
  ('crv-mal-4','soneva-maldives.com',CURRENT_DATE,2),('crv-mal-4','gili-lankanfushi.com',CURRENT_DATE,4),('crv-mal-4','anantara-maldives.com',CURRENT_DATE,8),
  ('crv-mal-5','soneva-maldives.com',CURRENT_DATE,3),('crv-mal-5','gili-lankanfushi.com',CURRENT_DATE,7),('crv-mal-5','anantara-maldives.com',CURRENT_DATE,13),
  ('crv-mal-6','soneva-maldives.com',CURRENT_DATE,2),('crv-mal-6','gili-lankanfushi.com',CURRENT_DATE,5),('crv-mal-6','anantara-maldives.com',CURRENT_DATE,11),
  ('crv-mal-7','soneva-maldives.com',CURRENT_DATE,1),('crv-mal-7','gili-lankanfushi.com',CURRENT_DATE,4),('crv-mal-7','anantara-maldives.com',CURRENT_DATE,7),
  ('crv-mal-8','soneva-maldives.com',CURRENT_DATE,4),('crv-mal-8','gili-lankanfushi.com',CURRENT_DATE,8),('crv-mal-8','anantara-maldives.com',CURRENT_DATE,12),
  ('crv-bal-1','alaya-ubud.com',CURRENT_DATE,2),('crv-bal-1','como-shambhala.com',CURRENT_DATE,5),('crv-bal-1','four-seasons-bali.com',CURRENT_DATE,8),
  ('crv-bal-2','alaya-ubud.com',CURRENT_DATE,NULL),('crv-bal-2','como-shambhala.com',CURRENT_DATE,NULL),('crv-bal-2','four-seasons-bali.com',CURRENT_DATE,NULL),
  ('crv-bal-3','alaya-ubud.com',CURRENT_DATE,3),('crv-bal-3','como-shambhala.com',CURRENT_DATE,7),('crv-bal-3','four-seasons-bali.com',CURRENT_DATE,11),
  ('crv-bal-4','alaya-ubud.com',CURRENT_DATE,4),('crv-bal-4','como-shambhala.com',CURRENT_DATE,6),('crv-bal-4','four-seasons-bali.com',CURRENT_DATE,10),
  ('crv-bal-5','alaya-ubud.com',CURRENT_DATE,5),('crv-bal-5','como-shambhala.com',CURRENT_DATE,9),('crv-bal-5','four-seasons-bali.com',CURRENT_DATE,14),
  ('crv-bal-6','alaya-ubud.com',CURRENT_DATE,7),('crv-bal-6','como-shambhala.com',CURRENT_DATE,12),('crv-bal-6','four-seasons-bali.com',CURRENT_DATE,16),
  ('crv-bal-7','alaya-ubud.com',CURRENT_DATE,3),('crv-bal-7','como-shambhala.com',CURRENT_DATE,8),('crv-bal-7','four-seasons-bali.com',CURRENT_DATE,13),
  ('crv-bal-8','alaya-ubud.com',CURRENT_DATE,9),('crv-bal-8','como-shambhala.com',CURRENT_DATE,14),('crv-bal-8','four-seasons-bali.com',CURRENT_DATE,21),
  ('hph-jai-1','taj-rambagh.com',CURRENT_DATE,2),('hph-jai-1','oberoi-rajvilas.com',CURRENT_DATE,5),('hph-jai-1','aman-bagh.com',CURRENT_DATE,9),
  ('hph-jai-2','taj-rambagh.com',CURRENT_DATE,NULL),('hph-jai-2','oberoi-rajvilas.com',CURRENT_DATE,NULL),('hph-jai-2','aman-bagh.com',CURRENT_DATE,NULL),
  ('hph-jai-3','taj-rambagh.com',CURRENT_DATE,3),('hph-jai-3','oberoi-rajvilas.com',CURRENT_DATE,7),('hph-jai-3','aman-bagh.com',CURRENT_DATE,12),
  ('hph-jai-4','taj-rambagh.com',CURRENT_DATE,5),('hph-jai-4','oberoi-rajvilas.com',CURRENT_DATE,10),('hph-jai-4','aman-bagh.com',CURRENT_DATE,16),
  ('hph-jai-5','taj-rambagh.com',CURRENT_DATE,4),('hph-jai-5','oberoi-rajvilas.com',CURRENT_DATE,8),('hph-jai-5','aman-bagh.com',CURRENT_DATE,13),
  ('hph-jai-6','taj-rambagh.com',CURRENT_DATE,3),('hph-jai-6','oberoi-rajvilas.com',CURRENT_DATE,6),('hph-jai-6','aman-bagh.com',CURRENT_DATE,10),
  ('hph-jai-7','taj-rambagh.com',CURRENT_DATE,2),('hph-jai-7','oberoi-rajvilas.com',CURRENT_DATE,5),('hph-jai-7','aman-bagh.com',CURRENT_DATE,8),
  ('hph-jai-8','taj-rambagh.com',CURRENT_DATE,7),('hph-jai-8','oberoi-rajvilas.com',CURRENT_DATE,12),('hph-jai-8','aman-bagh.com',CURRENT_DATE,19),
  ('zbh-ams-1','nhow-amsterdam.com',CURRENT_DATE,2),('zbh-ams-1','w-amsterdam.com',CURRENT_DATE,5),('zbh-ams-1','citizen-m.com',CURRENT_DATE,8),
  ('zbh-ams-2','nhow-amsterdam.com',CURRENT_DATE,NULL),('zbh-ams-2','w-amsterdam.com',CURRENT_DATE,NULL),('zbh-ams-2','citizen-m.com',CURRENT_DATE,NULL),
  ('zbh-ams-3','nhow-amsterdam.com',CURRENT_DATE,1),('zbh-ams-3','w-amsterdam.com',CURRENT_DATE,4),('zbh-ams-3','citizen-m.com',CURRENT_DATE,7),
  ('zbh-ams-4','nhow-amsterdam.com',CURRENT_DATE,3),('zbh-ams-4','w-amsterdam.com',CURRENT_DATE,7),('zbh-ams-4','citizen-m.com',CURRENT_DATE,11),
  ('zbh-ams-5','nhow-amsterdam.com',CURRENT_DATE,2),('zbh-ams-5','w-amsterdam.com',CURRENT_DATE,6),('zbh-ams-5','citizen-m.com',CURRENT_DATE,9),
  ('zbh-ams-6','nhow-amsterdam.com',CURRENT_DATE,4),('zbh-ams-6','w-amsterdam.com',CURRENT_DATE,9),('zbh-ams-6','citizen-m.com',CURRENT_DATE,14),
  ('zbh-ams-7','nhow-amsterdam.com',CURRENT_DATE,5),('zbh-ams-7','w-amsterdam.com',CURRENT_DATE,10),('zbh-ams-7','citizen-m.com',CURRENT_DATE,15),
  ('zbh-ams-8','nhow-amsterdam.com',CURRENT_DATE,6),('zbh-ams-8','w-amsterdam.com',CURRENT_DATE,12),('zbh-ams-8','citizen-m.com',CURRENT_DATE,18),
  ('hbh-edi-1','the-witchery.com',CURRENT_DATE,2),('hbh-edi-1','hotel-missoni-edinburgh.com',CURRENT_DATE,4),('hbh-edi-1','balmoral-hotel.com',CURRENT_DATE,7),
  ('hbh-edi-2','the-witchery.com',CURRENT_DATE,NULL),('hbh-edi-2','hotel-missoni-edinburgh.com',CURRENT_DATE,NULL),('hbh-edi-2','balmoral-hotel.com',CURRENT_DATE,NULL),
  ('hbh-edi-3','the-witchery.com',CURRENT_DATE,2),('hbh-edi-3','hotel-missoni-edinburgh.com',CURRENT_DATE,5),('hbh-edi-3','balmoral-hotel.com',CURRENT_DATE,9),
  ('hbh-edi-4','the-witchery.com',CURRENT_DATE,3),('hbh-edi-4','hotel-missoni-edinburgh.com',CURRENT_DATE,6),('hbh-edi-4','balmoral-hotel.com',CURRENT_DATE,10),
  ('hbh-edi-5','the-witchery.com',CURRENT_DATE,4),('hbh-edi-5','hotel-missoni-edinburgh.com',CURRENT_DATE,7),('hbh-edi-5','balmoral-hotel.com',CURRENT_DATE,12),
  ('hbh-edi-6','the-witchery.com',CURRENT_DATE,5),('hbh-edi-6','hotel-missoni-edinburgh.com',CURRENT_DATE,9),('hbh-edi-6','balmoral-hotel.com',CURRENT_DATE,14),
  ('hbh-edi-7','the-witchery.com',CURRENT_DATE,2),('hbh-edi-7','hotel-missoni-edinburgh.com',CURRENT_DATE,5),('hbh-edi-7','balmoral-hotel.com',CURRENT_DATE,8),
  ('hbh-edi-8','the-witchery.com',CURRENT_DATE,6),('hbh-edi-8','hotel-missoni-edinburgh.com',CURRENT_DATE,10),('hbh-edi-8','balmoral-hotel.com',CURRENT_DATE,15)
ON CONFLICT DO NOTHING;
